SELECT *
FROM TBL_CUSTOMER_INTERFACE
WHERE
    CUST_ID = 5411148

SELECT BILL_PERIOD, TR_PERIOD, TO_CHAR (BILL_NUM)
FROM TBL_SUB_LEDGER_DTL
WHERE
    CUST_ID = 5411148
    AND BILL_PERIOD = 202407

UPDATE tbl_bill_collection_hdr
SET
    bill_num = (
        SELECT bill_num
        FROM tbl_bill
        WHERE
            cust_id = 5411148
            AND bill_period = 202405
    )
WHERE
    cust_id = 5411148
    AND bill_period = 202405 100406068490005241
    
SELECT TO_CHAR (bill_num)
FROM tbl_bill
WHERE
    cust_id = 5411148
    AND bill_period = 202405

SELECT
    CN.CMO_ID,
    CN.CMO_DATE,
    CN.APP_TRK_NO,
    CN.SRNO,
    CN.CUST_ID,
    CN.ELAKA_CODE,
    CN.BOOK_CODE,
    CN.ACCOUNT_NUM,
    CN.CUST_NAME,
    C.CUSTOMER_ADDR_B AS CUST_ADDRESS,
    CN.MS_KHATIAN,
    CN.MS_DAGG,
    CN.MS_MOJA,
    CN.CMO_DISTRICT,
    CN.CMO_SUB_DISRTRICT,
    CN.CMO_UNION,
    CN.CMO_VILLAGE,
    CN.CMO_PO,
    CN.PO_CODE,
    CN.SPL_REMARKS,
    CN.CMO_COMPLETE_DATE,
    CN.EFF_PERIOD,
    CN.WIR_INS_ID,
    CN.WIR_DATE,
    CN.PHASE,
    CN.FSB_ID,
    CN.FSB_DATE,
    CN.MBR_SHIP_ID,
    CN.MBR_SHIP_NO,
    CN.CONNECTED_LOAD,
    CN.X_ID,
    CN.X_FORMER_POLE,
    CN.X_FORMER_LOAD,
    CN.SUBSTATION_ID,
    CN.FEEDER_ID,
    CN.FSB_OR_ID,
    CN.DEPOSIT_OR_ID,
    CN.CMO_STATUS,
    CN.CMO_PREPARED_BY,
    CN.CMO_BILLING_BY,
    CN.CMO_CONFIRMED_BY,
    CN.CMO_TYPE,
    CN.IS_INSTALL,
    CN.IS_CONNECT,
    CN.IS_REMOVE,
    CN.IS_DISCONNECT,
    CN.CREATE_BY,
    CN.CREATE_DATE,
    CN.UPDATE_BY,
    CN.UPDATE_DATE,
    CN.REC_STATUS,
    CN.CONN_DATE,
    CN.CONN_METER_ID,
    CN.CONN_METER_NO,
    CN.CONN_METER_DEGIT,
    CN.CON_METER_SEAL_NO,
    CN.CONN_METER_TYPE,
    CN.CONN_METER_VOLTAGE,
    CN.CONN_LOAD,
    CN.CONN_BY,
    CN.CONN_MF,
    CN.CONN_PF,
    CN.CONN_READING,
    CN.CONN_DEMAND_READING,
    CN.DISC_DATE,
    CN.DISC_METER_ID,
    CN.DISC_METER_NO,
    CN.DISC_METER_DEGIT,
    CN.DISC_METER_SEAL_NO,
    CN.DISC_METER_TYPE,
    CN.DISC_METER_VOLTAGE,
    CN.DISC_LOAD,
    CN.DISC_BY,
    CN.DISC_MF,
    CN.DISC_PF,
    CN.DISC_READING,
    CN.DISC_DEMAND_READING,
    CN.IS_PRINTED,
    CN.PRINT_DATE,
    CN.REMARKS,
    CN.CUST_MBR_SHIP_ID,
    CN.MBR_NON_VOTER,
    CN.MBR_SHIP_DATE,
    CN.MBR_SHIP_SR_NO_SPL,
    CN.MBR_SHIP_SR_NO,
    CN.MS_BOARD_NO,
    CN.MS_COMP_NAME,
    MS_NAME,
    (
        CASE
            WHEN CN.CMO_TYPE = 1 THEN CN.MS_FNAME
            ELSE F_H_NAME_B
        END
    ) MS_FNAME,
    CN.MS_MNAME,
    MS_HNAME,
    CN.MS_ADDRESS,
    CN.MS_PHONE,
    MS_EMAIL,
    CN.DOB,
    CN.MS_NATIONAL_ID,
    CN.MS_GENDER,
    CN.PIN_NO,
    CN.INS_ID,
    CN.INS_REF_NO,
    CN.INS_DATE,
    CN.TARIFF_CODE,
    CN.METER_TYPE_CODE,
    CN.WCONN_LOAD,
    CN.SERVICE_DROP_DISTANCE,
    CN.WIRING_INSPECTOR_EMP_CODE,
    CN.POLE_NO,
    CN.XFORMER_POLE_NO,
    CN.XFORMER_SL_NO,
    CN.NEAREST_POLE,
    CN.STATION_NAME,
    CN.STATION_NAME_B,
    CN.FEEDER_DESCR,
    CN.FEEDER_DESCR_B,
    OR_REF_ID,
    CN.OR_AMOUNT_TTL,
    CN.OR_DATE,
    SRT_NAME,
    CN.TARIFF_GRP_NAME_B,
    TARIFF_GRP_CODE,
    CN.TARIFF_NAME,
    TARIFF_GRP_NAME,
    CN.G_DIST_NAME,
    G_DIST_NAME_B,
    CN.G_SD_NAME,
    G_SD_NAME_B,
    CN.G_UNION_NAME,
    G_UNION_NAME_B,
    CN.G_VILL_NAME,
    CN.G_VILL_NAME_B,
    CN.G_PO_NAME,
    CN.G_PO_NAME_B,
    CN.MANF_DESCR,
    CN.MANF_DESCR_B,
    cm.DISC_UNIT
FROM
    VW_CMO_NEW CN
    inner join TBL_CMO cm ON cn.cmo_id = cm.CMO_ID
    left join tbl_customer_interface c ON cn.cust_id = c.cust_id
WHERE
    CN.CMO_ID = 38085