UPDATE TBL_JMENUS SET MENU_OPTION='20799' WHERE MENU_ID=20;
UPDATE TBL_JMENUS SET MENU_OPTION='1' WHERE MENU_ID=40;
UPDATE TBL_JMENUS SET MENU_OPTION='0' WHERE MENU_ID=123;
COMMIT;

UPDATE TBL_JMENUS SET MENU_OPTION='106405000000' WHERE MENU_ID=57;
commit;
---------------------------------------app track no--------------------------------