CREATE TABLE iebms.TBL_ONEPOINT (
  SERV_ID         NUMBER        NOT NULL,
  SERV_DATE       DATE,
  APPLICATION_NO  VARCHAR2 (50),
  CUST_ID         NUMBER,
  BOOK_CODE       VARCHAR2 (10),
  ACCOUNT_NUM     NUMBER,
  SERV_TYPE       VARCHAR2 (5)  NOT NULL,
  SERV_BY         VARCHAR2 (10),
  CREATE_BY       VARCHAR2 (10),
  CREATE_DATE     DATE          DEFAULT SYSDATE,
  UPDATE_BY       VARCHAR2 (10),
  UPDATE_DATE     DATE,
  SERV_DESCR      VARCHAR2 (255),
  OR_NUM          NUMBER,
  OR_AMOUNT_TTL   NUMBER (16,2),
  PRIMARY KEY ( SERV_ID ) );


CREATE TABLE iebms.TBL_OP_SERVICE_DTL (
  SERV_DTLID          NUMBER        NOT NULL,
  SERV_HDRID          NUMBER,
  COMPLAIN_TYPE_CODE  INTEGER       NOT NULL,
  DESCR               VARCHAR2 (500),
  ACTION              VARCHAR2 (500),
  ACTION_DATE         DATE,
  ACTION_BY           INTEGER,
  REC_STATUS          VARCHAR2 (1)  NOT NULL,
  CONSTRAINT TBL_OP_SERVICE_DTLID_PK
  PRIMARY KEY ( SERV_DTLID ) );

CREATE TABLE iebms.TBL_ONEPOINT_SERVICE_DTL (
  OP_SERV_DTLID        NUMBER        NOT NULL,
  OP_SERVID            NUMBER,
  COMPLAIN_TYPE_CODE   INTEGER       NOT NULL,
  COMPLAIN_DESCR_B     VARCHAR2 (200),
  COMPLAIN_DECISION_B  VARCHAR2 (200),
  PRIMARY KEY ( OP_SERV_DTLID ) );


CREATE TABLE TBL_ONEPOINT_SERVICE (
  OP_SERVID         NUMBER        NOT NULL,
  SERVICE_DATE      DATE          NOT NULL,
  CUST_ID           NUMBER,
  OFFICE_CODE       VARCHAR2 (2)  NOT NULL,
  ELAKA_CODE        VARCHAR2 (2),
  BOOK_CODE         VARCHAR2 (5),
  ACCOUNT_NUM       NUMBER,
  CUSTOMER_NAME_B   VARCHAR2 (50),
  F_H_NAME_B        VARCHAR2 (50),
  G_DIST_CODE       NUMBER,
  G_SD_CODE         NUMBER,
  G_UNION_CODE      NUMBER,
  G_VILL_CODE       NUMBER,
  COMPLAINT_NAME_B  VARCHAR2 (50),
  EMP_CODE          INTEGER,
  PAYTO_TYPE_CODE   INTEGER,
  FOR_REWIRING      VARCHAR2 (1),
  SERVICE_TIME      DATE,
  REC_STATUS        VARCHAR2 (1),
  CREATE_BY         VARCHAR2 (10),
  CREATE_DATE       DATE,
  UPDATE_BY         VARCHAR2 (10),
  UPDATE_DATE       DATE,
  PRIMARY KEY ( OP_SERVID )
 );
 