SELECT * FROM TBL_OFFICE_COLLECTION_MST WHERE COLL_TYPE = 4

SELECT * FROM TBL_OFFICE_COLLECTION_MST WHERE COLL_TYPE = 4
AND OR_NO IS NULL

UPDATE TBL_OFFICE_COLLECTION_MST SET or_no=or_num WHERE COLL_TYPE = 4
AND OR_NO IS NULL

SELECT * FROM TBL_OFFICE_COLLECTION_MST WHERE COLL_TYPE = 4
AND OR_NUM IS NULL

UPDATE TBL_OFFICE_COLLECTION_MST SET or_num='111111'  WHERE COLL_TYPE = 4
AND OR_NUM IS NULL


--UPDATE TBL_OFFICE_COLLECTION_MST SET or_num=or_no  WHERE COLL_TYPE = 4
--AND OR_NUM IS NULL



UPDATE TBL_OFFICE_COLLECTION_MST SET OR_NO='-'||OR_NO WHERE COLL_TYPE in (4,6) and or_num>0;
UPDATE TBL_OFFICE_COLLECTION_MST SET OR_NUM=-OR_NUM WHERE COLL_TYPE in (4,6) and or_num>0;

SELECT MAX(OFFM_COLL_ID) FROM TBL_OFFICE_COLLECTION_MST




