-------------------------- may be orcd/need to check---------------------------------------
UPDATE TBL_JMENUS SET MENU_OPTION='1' WHERE MENU_ID=40;
UPDATE TBL_JMENUS SET MENU_OPTION='301' WHERE MENU_ID=130;
UPDATE TBL_JMENUS SET MENU_OPTION='12' WHERE MENU_ID=35;
UPDATE TBL_JMENUS SET MENU_OPTION='1' WHERE MENU_ID=123;

commit;