CREATE OR REPLACE VIEW VW_CUSTOMER_FULL_INFO  AS SELECT CI.CUST_INTFID, 
CI.CUST_ID, REF_CUSTOMER_NUM, CI.OFFICE_CODE, ELAKA_CODE, 
CI.BOOK_CODE, CI.ACCOUNT_NUM, CI.TARIFF_CODE, CUSTOMER_NAME, 
CUSTOMER_NAME_B, F_H_NAME, F_H_NAME_B, AGE, 
DOB, REL_SHIP_CODE, MOTHER_NAME, MOTHER_NAME_B, 
CI.G_DIST_CODE, CI.G_SD_CODE, CI.G_UNION_CODE, CI.G_VILL_CODE, 
G_PO_CODE, CUSTOMER_ADDR, CUSTOMER_ADDR_B, ORDER_TYPE_CODE, 
ORDER_DATE, ORDER_END_DATE, DISCON_DATE, PHASE, 
METER_TYPE_CODE, METER_NUM, METER_DIGIT, METER_SEAL_NUM, 
MF, PF, CONN_CAT_CODE, FIRST_CONN_DATE, 
MBR_SHIP_NO, MBR_SHIP_FEE, LOAD_UNIT_CODE, SANCTIONED_LOAD, 
CONNECTED_LOAD, IS_OWN_XFORMER, IS_USER_XFORMER, IS_OWN_GENERATOR, 
IS_COMPLEX, IS_MIN_BILL, CUST_SPL_TYPE, METER_SPL_TYPE, 
PARENT_METER_ID, REF_ADJTARIFF_CODE, REF_ADJTARIFF_OFFPK_UNIT, CUST_SRC_CODE, 
IS_METER_INSTALMENT, METER_PRICE, METER_INSTALMENT_AMT, INSTALMENT_PERIOD, 
NOF_LIGHT, IS_REFUND_DEPOSIT, IS_CI_REBATE, REBATE_UPTO_OFFPK_UNIT, 
REBATE_UPTO_PK_UNIT, SEASON_TYPE_CODE, SEASON_DATE, SEASON_MIN_CHARGE, 
SEASON_START_MONTH, CI.EFF_BILL_PERIOD, MIN_OWNER_CODE, MIN_ORG_CODE, 
EBA_X, CI.REC_STATUS, CI.CREATE_BY, CI.CREATE_DATE, 
CI.UPDATE_BY, CI.UPDATE_DATE, MBR_SHIP_DATE, MBR_PICTURE, 
MBR_NON_VOTER, SPL_REBATE_OFFPK_UNIT, MBR_SHIP_SR_NO_SPL, MBR_SHIP_SR_NO, 
PF_MSR_DATE, CUST_METER_ID, AVG_UNIT, SUBSTATION_ID, 
CI.FEEDER_ID, X_ID, X_SERIAL, NEAREST_POLE, 
OP_READING,TF.SRT_NAME,TF.TARIFF_GRP_NAME_B,TF.TARIFF_GRP_CODE,TF.TARIFF_NAME,TF.TARIFF_GRP_NAME,
G_DIST_NAME, G_DIST_NAME_B,  G_SD_NAME, G_SD_NAME_B, G_UNION_NAME, G_UNION_NAME_B,  G_VILL_NAME, G_VILL_NAME_B
,S.STATION_NAME,S.STATION_NAME_B,F.FEEDER_DESCR, F.FEEDER_DESCR_B,
MSC.NATIONAL_ID_NO, MSC.PIN, MSC.DEPOSIT_NO, MSC.DEPOSIT_DATE, MSC.DEPOSIT_AMT, MSC.LEGAL_OWNER_B, 
MSC.LEGAL_OWNER, MSC.MOUZA_B, MSC.MOUZA, MSC.DAGG_NO, MSC.POLE_DIST, MSC.SPL_INFO, MSC.MOBILE_NO_1, 
MSC.MOBILE_NO_2 FROM TBL_CUSTOMER_INTERFACE  CI
inner  join VW_TARIFF TF ON  CI.TARIFF_CODE=TF.TARIFF_CODE
inner join vw_G_VILLAGE G ON CI.G_VILL_CODE=G.G_VILL_CODE
left join tbl_sub_station  S ON CI.SUBSTATION_ID=S.SUB_STATION_CODE
left join TBL_FEEDER F ON  CI.FEEDER_ID=F.FEEDER_CODE
left join TBL_XFORMERS XF ON CI.X_ID=XF.XF_ID
left join TBL_CUSTOMER_MISC_INFO MSC ON CI.CUST_ID=MSC.CUST_ID;










CREATE OR REPLACE VIEW VW_CMO_NEW
 AS SELECT CMO_ID, CMO_DATE, APP_TRK_NO, CMO.SRNO, CMO.CUST_ID, CMO.ELAKA_CODE, CMO.BOOK_CODE, CMO.ACCOUNT_NUM, 
CUST_NAME, CUST_ADDRESS, MBR.MS_KHATIAN, MBR.MS_DAGG, MBR.MS_MOJA, CMO_DISTRICT, CMO_SUB_DISRTRICT, CMO_UNION, CMO_VILLAGE, 
CMO_PO, PO_CODE, SPL_REMARKS, CMO_COMPLETE_DATE, EFF_PERIOD, WIR_INS_ID, WIR_DATE, CMO.PHASE, FSB_ID, FSB_DATE, MBR_SHIP_ID, 
CMO.MBR_SHIP_NO, CONNECTED_LOAD, CMO.X_ID, X_FORMER_POLE, X_FORMER_LOAD, SUBSTATION_ID, CMO.FEEDER_ID, FSB_OR_ID, DEPOSIT_OR_ID, 
CMO_STATUS, CMO_PREPARED_BY, CMO_BILLING_BY, CMO_CONFIRMED_BY, CMO_TYPE, IS_INSTALL, IS_CONNECT, IS_REMOVE, IS_DISCONNECT, 
CMO.CREATE_BY, CMO.CREATE_DATE, CMO.UPDATE_BY, CMO.UPDATE_DATE, CMO.REC_STATUS, CONN_DATE, CONN_METER_ID, CONN_METER_NO, CONN_METER_DEGIT, 
CON_METER_SEAL_NO, CONN_METER_TYPE, CONN_METER_VOLTAGE, CMO.CONN_LOAD, CONN_BY, CONN_MF, CONN_PF, CONN_READING, 
CONN_DEMAND_READING, DISC_DATE, DISC_METER_ID, DISC_METER_NO, DISC_METER_DEGIT, DISC_METER_SEAL_NO, DISC_METER_TYPE, 
DISC_METER_VOLTAGE, DISC_LOAD, DISC_BY, DISC_MF, DISC_PF, DISC_READING, DISC_DEMAND_READING, IS_PRINTED, PRINT_DATE, REMARKS,
MBR.CUST_MBR_SHIP_ID,MBR.MBR_NON_VOTER,MBR_SHIP_DATE, MBR_SHIP_SR_NO_SPL, MBR_SHIP_SR_NO, MS_BOARD_NO, MS_COMP_NAME, 
MS_NAME, MS_FNAME, MS_MNAME, MS_HNAME, MS_ADDRESS, MS_PHONE, MS_EMAIL, DOB,
MS_NATIONAL_ID, MS_GENDER,PIN_NO,
WI.INS_ID,WI.INS_REF_NO, INS_DATE, WI.TARIFF_CODE, METER_TYPE_CODE, WI.CONN_LOAD AS WCONN_LOAD, SERVICE_DROP_DISTANCE,
WIRING_INSPECTOR_EMP_CODE, POLE_NO, XFORMER_POLE_NO, XFORMER_SL_NO, NEAREST_POLE,
ST.STATION_NAME, ST.STATION_NAME_B,F.FEEDER_DESCR, F.FEEDER_DESCR_B,RP.OR_REF_ID, RP.OR_AMOUNT_TTL,RP.OR_DATE ,
TF.SRT_NAME,TF.TARIFF_GRP_NAME_B,TF.TARIFF_GRP_CODE,TF.TARIFF_NAME,TF.TARIFF_GRP_NAME,
VLG.G_DIST_NAME, VLG.G_DIST_NAME_B, VLG.G_SD_NAME, VLG.G_SD_NAME_B, VLG.G_UNION_NAME, VLG.G_UNION_NAME_B, 
VLG.G_VILL_NAME, VLG.G_VILL_NAME_B,P.G_PO_NAME,P.G_PO_NAME_B,
MTR.MANF_DESCR,MTR.MANF_DESCR_B
FROM TBL_CMO CMO LEFT JOIN VW_G_VILLAGE VLG ON CMO.CMO_VILLAGE=VLG.G_VILL_CODE
left join  TBL_CUSTOMER_MBR_SHIP MBR ON CMO.MBR_SHIP_ID=MBR.CUST_MBR_SHIP_ID
LEFT JOIN TBL_WIRING_INSPECTION WI ON  CMO.WIR_INS_ID=WI.INS_ID
LEFT JOIN  TBL_SUB_STATION ST ON CMO.SUBSTATION_ID=ST.SUB_STATION_CODE
LEFT JOIN TBL_FEEDER F ON CMO.FEEDER_ID=F.FEEDER_CODE
LEFT JOIN TBL_OFFICE_RECIEPT RP ON CMO.DEPOSIT_OR_ID=RP.OR_ID
LEFT JOIN VW_METER_INFO MTR ON CMO.CONN_METER_ID=MTR.METER_ID
LEFT JOIN VW_TARIFF TF ON WI.TARIFF_CODE=TF.TARIFF_CODE
LEFT JOIN TBL_G_POST_OFFICE P ON CMO.CMO_PO=P.G_PO_CODE;





CREATE OR REPLACE VIEW VW_SUB_LEDGER_J 
 AS SELECT   LEDGER_DTLID,L.CUST_ID, L.BILL_PERIOD, L.TR_PERIOD, L.BILL_MONTH_B,  BILL_NUM, 
 BILL_ISSUE_DATE, L.BILL_LPC1_DATE, L.BILL_DISCON_DATE, L.BILL_LPC2_DATE, L.TR_DATE,
  L.ROW_TYPE, L.METER_READING, USEDUNIT, NVL(AMOUNT_SALES,0) AS AMOUNT_NET, 
NVL(( CASE WHEN NVL(AMOUNT_SALES,0)=0  THEN DMCM_AMT ELSE 0 END),0)  DMCM_AMT_NET, AMOUNT_VAT, DMCM_AMT_VAT, AMOUNT_REBATE_VAT_AMT, 
DMCM_REBATE_VAT_AMT, AMOUNT_LPC_1, DMCM_AMT_LPC_1, AMOUNT_LPC_2, DMCM_AMT_LPC_2, AMOUNT_DCRC, AMOUNT_METER_RENT, 
AMOUNT_MISC, AMOUNT_OTHER_AMT, PAID_DATE,
NVL( PAID_SALES,0) AS PAID_NET, PAID_VAT, PAID_REBATE_VAT_AMT, PAID_LPC_1, PAID_LPC_2, PAID_DCRC, PAID_METER_RENT, PAID_MISC, PAID_OTHER_AMT, PAID_EXTRA_NET, L.REMARKS_B, L.CREATE_BY, L.CREATE_DATE, L.REC_STATUS, L.BOOK_CODE, L.ACCOUNT_NUM, L_TR_ID, L_TR_REMARKS, L_TR_STATUS, CI.ACCOUNT_NUM AS ACCNUM, CI.BOOK_CODE AS BOOK, CI.ELAKA_CODE AS EKAKA, CI.CUSTOMER_NAME_B, CI.F_H_NAME_B,CI.REF_CUSTOMER_NUM, OFFICE_CODE, AGE, DOB, REL_SHIP_CODE, G_PO_CODE, CUSTOMER_ADDR, CUSTOMER_ADDR_B, PHASE, MF, PF, CONN_CAT_CODE, FIRST_CONN_DATE, IS_OWN_XFORMER, IS_USER_XFORMER, IS_OWN_GENERATOR, IS_COMPLEX, CUST_SPL_TYPE, METER_SPL_TYPE, PARENT_METER_ID, CUST_SRC_CODE, NOF_LIGHT, SEASON_TYPE_CODE, SEASON_DATE, SEASON_START_MONTH ,G.G_VILL_NAME_B,G.G_UNION_NAME_B,G.G_SD_NAME_B,G.G_DIST_NAME_B  , CI.METER_NUM, ROUND(CI.SANCTIONED_LOAD,2) AS SANC_LOAD, T.TARIFF_NAME_B,CI.TARIFF_CODE,L.PAID_REBATE,L.PAID_SUBSIDY,L.PAID_NET AS P_NET,AMOUNT_NET AS NETBILL,S_METER_NUM,AMOUNT_SUBSIDY,AMOUNT_REBATE FROM TBL_SUB_LEDGER_DTL L INNER JOIN TBL_CUSTOMER_INTERFACE CI ON L.CUST_ID=CI.CUST_ID INNER JOIN VW_G_VILLAGE G ON G.G_VILL_CODE=CI.G_VILL_CODE INNER JOIN TBL_TARIFF T ON T.TARIFF_CODE=CI.TARIFF_CODE;













