ALTER TABLE IEBMS.TBL_BILL_CORR MODIFY MIN_OWNER_DESCR_B VARCHAR2(300);
ALTER TABLE IEBMS.TBL_BILL_CORR MODIFY TARIFF_RATE_DESCR_B VARCHAR2(300);
ALTER TABLE IEBMS.TBL_BILL_CORR MODIFY XFORMER_RENT_REMARKS VARCHAR2(500);
ALTER TABLE IEBMS.TBL_BILL_CORR MODIFY XFORMER_PRICE_REMARKS VARCHAR2(500);
ALTER TABLE IEBMS.TBL_BILL_CORR MODIFY LPC_REMARKS VARCHAR2(500);
ALTER TABLE IEBMS.TBL_BILL_CORR MODIFY METER_PRICE_REMARKS VARCHAR2(500);
ALTER TABLE IEBMS.TBL_BILL_CORR MODIFY DCRC_REMARKS VARCHAR2(500);

ALTER TABLE IEBMS.TBL_BILL MODIFY MIN_OWNER_DESCR_B VARCHAR2(300);
ALTER TABLE IEBMS.TBL_BILL MODIFY TARIFF_RATE_DESCR_B VARCHAR2(300);
ALTER TABLE IEBMS.TBL_BILL MODIFY FEEDER_CODE VARCHAR2(50);
ALTER TABLE IEBMS.TBL_BILL MODIFY XFORMER_RENT_REMARKS VARCHAR2(500);
ALTER TABLE IEBMS.TBL_BILL MODIFY XFORMER_PRICE_REMARKS VARCHAR2(500);
ALTER TABLE IEBMS.TBL_BILL MODIFY LPC_REMARKS VARCHAR2(500);
ALTER TABLE IEBMS.TBL_BILL MODIFY METER_PRICE_REMARKS VARCHAR2(500);
ALTER TABLE IEBMS.TBL_BILL MODIFY DCRC_REMARKS VARCHAR2(500);


UPDATE TBL_TARIFF SET B_FORM='-';

UPDATE TBL_TARIFF SET B_FORM='LTA' WHERE TARIFF_GRP_CODE = 1;

UPDATE TBL_TARIFF SET B_FORM='LTO'
WHERE TARIFF_GRP_CODE IN (SELECT TARIFF_GRP_CODE FROM TBL_TARIFF_GROUP WHERE TENS_NAME='LT' AND TARIFF_GRP_CODE <> 1 OR TARIFF_GRP_CODE IN (9,10,11));

UPDATE TBL_TARIFF SET B_FORM='HT'
WHERE TARIFF_GRP_CODE IN (SELECT TARIFF_GRP_CODE FROM TBL_TARIFF_GROUP WHERE TENS_NAME IN ('EHT','HT','MT'));


UPDATE TBL_JMENUS
SET MENU_OPTION='11272998:A2544,O5088,T3816'
WHERE 
MENU_ID=99;
COMMIT;