SELECT TENS_NAME||'-'||TENS_NAME_sub AS Class, SUM(NVL(CONNECTED_LOAD,0)) AS JUNE_22
FROM TBL_BILL b, TBL_TARIFF_GROUP T WHERE B.TARIFF_GRP_CODE=T.TARIFF_GRP_CODE
AND BILL_PERIOD=202206 AND t.tariff_grp_code <>11 AND tariff_code NOT IN (51,52)
GROUP BY t.TARIFF_GRP_CODE, BILL_PERIOD,TENS_NAME||'-'||TENS_NAME_sub

UNION ALL

SELECT TENS_NAME||'-'||TENS_NAME_sub||' Office', SUM(NVL(CONNECTED_LOAD,0)) AS JUNE_22
FROM TBL_BILL b, TBL_TARIFF_GROUP T WHERE B.TARIFF_GRP_CODE=T.TARIFF_GRP_CODE
AND BILL_PERIOD=202206 AND t.tariff_grp_code <>11 AND tariff_code IN (51,52)
GROUP BY t.TARIFF_GRP_CODE, BILL_PERIOD,TENS_NAME||'-'||TENS_NAME_sub

ORDER BY class