




ALTER TABLE table_name
DROP CONSTRAINT constraint_name(primary key name);




ALTER TABLE table_name
ADD CONSTRAINT constraint_name(primary key name) 
PRIMARY KEY (column1, column2, ...);




ALTER TABLE IEBMS.TBL_METER_READING_DTL ADD CONSTRAINT READING_DTLID_PK PRIMARY KEY (READING_DTLID);
ALTER TABLE IEBMS.TBL_BILL ADD CONSTRAINT BILL_NUM_PK PRIMARY KEY (BILL_NUM);
ALTER TABLE IEBMS.TBL_BILL_COLLECTION_HDR ADD CONSTRAINT COLL_NUM_PK PRIMARY KEY (COLL_NUM);
ALTER TABLE IEBMS.TBL_SUB_LEDGER_DTL ADD CONSTRAINT LEDGER_DTLID_PK PRIMARY KEY (LEDGER_DTLID);
ALTER TABLE IEBMS.TBL_BILL_ARREAR_HDR ADD CONSTRAINT TBL_ARR_PK PRIMARY KEY (BILL_PERIOD, CUST_ID, ARR_BILL_PERIOD,BILL_NUM);