----------------------------------arrear table index ----------------------------------------
CREATE INDEX IEBMS.TBL_BILL_ARRHDR_CPRC_INDX ON "IEBMS".TBL_BILL_ARREAR_HDR(CUST_ID, BILL_PERIOD, REC_STATUS);

CREATE INDEX IEBMS.TBL_BILL_ARRHDR_CIBPDC_INDX ON "IEBMS".TBL_BILL_ARREAR_HDR(CUST_ID, BILL_PERIOD, LAST_DISCON_DATE);

CREATE INDEX IEBMS.TBL_BILL_ARRHDR_BP_BN_INDX ON "IEBMS".TBL_BILL_ARREAR_HDR(BILL_PERIOD, BILL_NUM);

CREATE INDEX IEBMS.TBL_BILL_ARRHDR_BPBA_INDX ON "IEBMS".TBL_BILL_ARREAR_HDR(BILL_PERIOD, BAL_EXTRA_PAY_AMT, ARR_BILL_ID);

CREATE INDEX IEBMS.TBL_BILL_ARRHDR_CIBPABPDC_INDX ON "IEBMS".TBL_BILL_ARREAR_HDR(
  CUST_ID,
  BILL_PERIOD,
  ARR_BILL_PERIOD,
  LAST_DISCON_DATE
);

CREATE INDEX IEBMS.TBL_BILL_ARRHDR_BP_INDX ON "IEBMS".TBL_BILL_ARREAR_HDR(BILL_PERIOD);

CREATE INDEX IEBMS.TBL_BILL_ARRHDR_CERT_INDX ON "IEBMS".TBL_BILL_ARREAR_HDR(
  CUST_ID,
  ARR_BILL_PERIOD,
  BILL_PERIOD,
  ARR_NET_BILL_AMT
);

CREATE INDEX IEBMS.TBL_BILL_ARRHDR_BILL_NUM_INDX ON "IEBMS".TBL_BILL_ARREAR_HDR(BILL_NUM);

CREATE INDEX IEBMS.TBL_BILL_ARRHDR_ARRBILLID_INDX ON "IEBMS".TBL_BILL_ARREAR_HDR(ARR_BILL_ID);

CREATE INDEX IEBMS.TBL_BILL_ARRHDR_CIBP_UK ON "IEBMS".TBL_BILL_ARREAR_HDR(CUST_ID, BILL_PERIOD);

---------------------------------------------bill table index--------------------------------------------------
CREATE UNIQUE INDEX IEBMS.TBL_BILL_CI_BP_BT_UK ON "IEBMS".TBL_BILL(CUST_ID, BILL_PERIOD, BILL_TYPE);

CREATE INDEX IEBMS.TBL_BILL_SMS_BILLPRINT_INDX ON "IEBMS".TBL_BILL(BILL_NUM, BILL_PERIOD, BILL_ISSUE_DATE);

CREATE INDEX IEBMS.TBL_BILL_BP_BILLNUM_UK ON "IEBMS".TBL_BILL(BOOK_CODE, BILL_PERIOD, BILL_NUM);

CREATE INDEX IEBMS.TBL_BILL_CUST_ID__UK ON "IEBMS".TBL_BILL(CUST_ID, BILL_PERIOD);

CREATE INDEX IEBMS.TBL_CUSTOMER_METER_CUST_ID_UK ON "IEBMS".TBL_BILL(CUST_ID);

CREATE INDEX IEBMS.TBL_BILL_BP_ACBILL_NUM_UK ON "IEBMS".TBL_BILL(BOOK_CODE, BILL_PERIOD, ACCOUNT_NUM, BILL_NUM);

CREATE INDEX IEBMS.TBL_BILL_PRINT_UK ON "IEBMS".TBL_BILL(
  BILL_ISSUE_DATE,
  BILL_LPC1_DATE,
  BILL_LPC2_DATE,
  BILL_DISCON_DATE,
  BOOK_CODE,
  BILL_PERIOD,
  ACCOUNT_NUM,
  BILL_NUM
);

CREATE INDEX IEBMS.TBL_BILL_MONSUM_INDX ON "IEBMS".TBL_BILL(BOOK_CODE, TARIFF_CODE, BILL_PERIOD, REC_STATUS);

CREATE INDEX IEBMS.TBL_BILL_BP_BT_UK ON "IEBMS".TBL_BILL(BILL_PERIOD, BILL_TYPE);

CREATE INDEX IEBMS.TBL_BILL_MONSUM_PROC_INDX ON "IEBMS".TBL_BILL(
  BILL_ISSUE_DATE,
  BILL_LPC1_DATE,
  BILL_LPC2_DATE,
  BILL_DISCON_DATE,
  BOOK_CODE,
  TARIFF_CODE,
  BILL_PERIOD,
  REC_STATUS
);

CREATE INDEX IEBMS.TBL_BILL_BNCI_INDX ON "IEBMS".TBL_BILL(BILL_NUM, CUST_ID);

CREATE INDEX IEBMS.TBL_BILL_PRINTDUE_INDX ON "IEBMS".TBL_BILL(
  BILL_NUM,
  BILL_ISSUE_DATE,
  BILL_LPC1_DATE,
  BILL_LPC2_DATE,
  BILL_DISCON_DATE
);

CREATE INDEX IEBMS.TBL_CUSTOMER_METER_BKBP_INDX ON "IEBMS".TBL_BILL(BOOK_CODE, BILL_PERIOD);

CREATE INDEX IEBMS.TBL_BILL_BOOKEMPCODE_INDX ON "IEBMS".TBL_BILL(BOOK_EMP_CODE);

CREATE UNIQUE INDEX IEBMS.TBL_BILL_BILL_NUM_UK ON "IEBMS".TBL_BILL(BILL_NUM);

CREATE INDEX IEBMS.TBL_BILL_CI_BP_RC_UK ON "IEBMS".TBL_BILL(CUST_ID, BILL_PERIOD, REC_STATUS);

CREATE INDEX IEBMS.TBL_BILL_LDGR_INDX ON "IEBMS".TBL_BILL(
  BILL_ISSUE_DATE,
  BILL_LPC1_DATE,
  BILL_LPC2_DATE,
  BILL_DISCON_DATE,
  CUST_ID,
  BILL_PERIOD
);

CREATE INDEX IEBMS.TBL_BILL_BNRC_INDX ON "IEBMS".TBL_BILL(BILL_NUM, REC_STATUS);

CREATE INDEX IEBMS.TBL_BILL_BPRC_INDX ON "IEBMS".TBL_BILL(BILL_PERIOD, REC_STATUS);

CREATE INDEX IEBMS.TBL_BILL_BPBTRC_INDX ON "IEBMS".TBL_BILL(BILL_PERIOD, BILL_TYPE, REC_STATUS);

CREATE INDEX IEBMS.TBL_BILL_BNCIBPRC_INDX ON "IEBMS".TBL_BILL(BILL_NUM, CUST_ID, BILL_PERIOD, REC_STATUS);

CREATE INDEX IEBMS.TBL_BILL_LDGR_F_INDX ON "IEBMS".TBL_BILL(
  BILL_NUM,
  BILL_ISSUE_DATE,
  BILL_LPC1_DATE,
  BILL_LPC2_DATE,
  BILL_DISCON_DATE,
  CUST_ID,
  BILL_PERIOD
);

CREATE INDEX IEBMS.INDX_BILL_CREATE ON "IEBMS".TBL_BILL(CREATE_DATE);

CREATE INDEX IEBMS.TBL_METER_READING_DTL_ID_INDX ON "IEBMS".TBL_BILL(READING_ID);

CREATE INDEX IEBMS.INDX_TBL_BILL_READING_DTL_ID ON "IEBMS".TBL_BILL(BILL_NUM, READING_ID);

CREATE INDEX IEBMS.TBL_BILL_BILLSHEET_INDX ON "IEBMS".TBL_BILL(
  BILL_ISSUE_DATE,
  BILL_LPC1_DATE,
  BILL_LPC2_DATE,
  BILL_DISCON_DATE,
  BILL_PERIOD,
  BOOK_CODE,
  BILL_TYPE
);

CREATE INDEX IEBMS.TBL_BILL_BPTG_INDX ON "IEBMS".TBL_BILL(BILL_PERIOD, TARIFF_GRP_CODE);

CREATE INDEX IEBMS.TBL_BILL_CBID_INDX ON "IEBMS".TBL_BILL(CHARGE_BASE_ID);

-------------------------------------meter reading table script--------------------------------
CREATE INDEX IEBMS.TBL_MR_DTL_READING_ID ON "IEBMS".TBL_METER_READING_DTL(READING_ID);

CREATE INDEX IEBMS.READING_METER_SPL_TYPE_INDX ON "IEBMS".TBL_METER_READING_DTL(METER_SPL_TYPE);

CREATE INDEX IEBMS.READING_REC_STATUS_TYPE_INDX ON "IEBMS".TBL_METER_READING_DTL(REC_STATUS);

CREATE INDEX IEBMS.MR_DTL_CUST_ID_BILL_PERIOD_UK ON "IEBMS".TBL_METER_READING_DTL(CUST_ID, BILL_PERIOD);

CREATE INDEX IEBMS.MR_DTL_CUST_ID_UK ON "IEBMS".TBL_METER_READING_DTL(CUST_ID);

CREATE INDEX IEBMS.TBL_MR_DTL_COMB ON "IEBMS".TBL_METER_READING_DTL(
  READING_ID,
  BILL_PERIOD,
  METER_ID,
  METER_TYPE_CODE,
  TOD_CODE,
  TIME_CYCLE_CODE,
  READING_TYPE_CODE,
  READING_SRNO,
  READING_PROCESS_FLAG,
  REC_STATUS
);

CREATE INDEX IEBMS.TBL_MR_DTL_BPMIRPF_UK ON "IEBMS".TBL_METER_READING_DTL(
  BILL_PERIOD,
  PARENT_METER_ID,
  READING_PROCESS_FLAG
);

CREATE INDEX IEBMS.MR_DTL_CI_BP_RP_FLAG_IDX ON "IEBMS".TBL_METER_READING_DTL(CUST_ID, BILL_PERIOD, READING_PROCESS_FLAG);

CREATE INDEX IEBMS.MR_DTL_CI_BP_ISADJ_INDX ON "IEBMS".TBL_METER_READING_DTL(CUST_ID, BILL_PERIOD, IS_ADJ_IRRIBILL);

CREATE INDEX IEBMS.MR_DTL_BPRP_FLAG ON "IEBMS".TBL_METER_READING_DTL(BILL_PERIOD, READING_PROCESS_FLAG);

CREATE INDEX IEBMS.MR_DTL_CIBPRI_INDX ON "IEBMS".TBL_METER_READING_DTL(CUST_ID, BILL_PERIOD, READING_ID);

CREATE INDEX IEBMS.TBL_MR_CBID_INDX ON "IEBMS".TBL_METER_READING_DTL(CHARGE_BASE_ID);

CREATE INDEX IEBMS.TBL_MTR_READ_DTL_INDX ON "IEBMS".TBL_METER_READING_DTL(
  READING_ID,
  CUST_ID,
  BILL_PERIOD,
  READING_PROCESS_FLAG,
  READING_TYPE_CODE,
  USE_PK
);

---------------------------------------tbl bill corr -------------------------------------
CREATE INDEX IEBMS.TBL_COLL_HDR_POINT_COLL_DATE ON "IEBMS".TBL_BILL_COLLECTION_HDR(POINT_CODE, COLL_DATE);

CREATE INDEX IEBMS.TBL_COLL_HDR_BILL_NUM ON "IEBMS".TBL_BILL_COLLECTION_HDR(BILL_NUM);

CREATE INDEX IEBMS.COLLECTION_HDR_BATCH ON "IEBMS".TBL_BILL_COLLECTION_HDR(BATCH_ID);

CREATE INDEX IEBMS.OFFICE_SRC_REF_ID_INDX ON "IEBMS".TBL_BILL_COLLECTION_HDR(SRC_REF_ID);

CREATE INDEX IEBMS.IDX_COLL_PERIOD ON "IEBMS".TBL_BILL_COLLECTION_HDR(COLL_BILL_PERIOD, CUST_ID);

CREATE INDEX IEBMS.IDX_COLL_DATE ON "IEBMS".TBL_BILL_COLLECTION_HDR(BOOK_CODE, COLL_DATE, CREATE_DATE);

CREATE INDEX IEBMS.IDX_LPC_ERR ON "IEBMS".TBL_BILL_COLLECTION_HDR(LPC1_ERR, LPC2_ERR, DUP_ERR);

CREATE INDEX IEBMS.TBL_BILL_COLLHDR_MONSUM_INDX ON "IEBMS".TBL_BILL_COLLECTION_HDR(CUST_ID, TARIFF_CODE, COLL_BILL_PERIOD);

CREATE INDEX IEBMS.TBL_COLL_HDR_PCBN_INDX ON "IEBMS".TBL_BILL_COLLECTION_HDR(BILL_NUM, POINT_CODE);

CREATE INDEX IEBMS.TBL_BILL_COLLHDR_BCBR_INDX ON "IEBMS".TBL_BILL_COLLECTION_HDR(BILL_NUM, COLL_BILL_PERIOD, REC_STATUS);

CREATE INDEX IEBMS.TBL_COLLHDR_MONSUM_INDX ON "IEBMS".TBL_BILL_COLLECTION_HDR(
  BOOK_CODE,
  TARIFF_CODE,
  COLL_BILL_PERIOD,
  REC_STATUS
);

CREATE INDEX IEBMS.TBL_COLL_HDR_POINT_BILL_NUM ON "IEBMS".TBL_BILL_COLLECTION_HDR(POINT_CODE, BILL_NUM);

CREATE INDEX IEBMS.TBL_COLL_HDR_BP_RC_INDX ON "IEBMS".TBL_BILL_COLLECTION_HDR(COLL_BILL_PERIOD, REC_STATUS);

CREATE INDEX IEBMS.TBL_BILL_COLLHDR_CIBPCTRC_INDX ON "IEBMS".TBL_BILL_COLLECTION_HDR(CUST_ID, COLL_BILL_PERIOD, COLL_TYPE, REC_STATUS);

CREATE INDEX IEBMS.TBL_COLLHDR_BNCBPCDTRC_INDX ON "IEBMS".TBL_BILL_COLLECTION_HDR(
  BILL_NUM,
  COLL_BILL_PERIOD,
  COLL_DATE,
  REC_STATUS
);

CREATE INDEX IEBMS.TBL_COLL_HDR_CIRC_INDX ON "IEBMS".TBL_BILL_COLLECTION_HDR(CUST_ID, REC_STATUS);

--------------------------------------------------tbl_customer_interface---------------------------------------------------
CREATE UNIQUE INDEX IEBMS.CUSTOMER_INT_CUST_INTFID_PK ON "IEBMS".TBL_CUSTOMER_INTERFACE(CUST_INTFID);

CREATE INDEX IEBMS.TBL_CUSTOMER_INTF_BKRC_INDX ON "IEBMS".TBL_CUSTOMER_INTERFACE(BOOK_CODE, REC_STATUS);

CREATE INDEX IEBMS.TBL_CUSTOMER_INTF_BKACRC_INDX ON "IEBMS".TBL_CUSTOMER_INTERFACE(BOOK_CODE, ACCOUNT_NUM, REC_STATUS);

CREATE INDEX IEBMS.TBL_CUSTOMER_INTF_CIBKAC_INDX ON "IEBMS".TBL_CUSTOMER_INTERFACE(CUST_ID, BOOK_CODE, ACCOUNT_NUM);

CREATE INDEX IEBMS.TBL_CUSTOMER_INTF_CI_INDX ON "IEBMS".TBL_CUSTOMER_INTERFACE(CUST_ID);

CREATE UNIQUE INDEX IEBMS.TBL_CUST_NTERFACE_BA_INDX ON "IEBMS".TBL_CUSTOMER_INTERFACE(BOOK_CODE, ACCOUNT_NUM);

---------------------------------------------------tbl arrcomb dtl---------------------------------------------------------
CREATE INDEX IEBMS.TBL_BILL_ARRCOTL_MAIN ON "IEBMS".TBL_BILL_ARRCOMB_DTL(PROC_BILL_PERIOD, PROC_BILL_NUM, REC_STATUS);

CREATE INDEX IEBMS.TBL_BILL_ARRCOMB_DTL_MAIN ON "IEBMS".TBL_BILL_ARRCOMB_DTL(
  CUST_ID,
  PROC_BILL_PERIOD,
  PROC_BILL_NUM,
  BILL_NUM
);

CREATE UNIQUE INDEX IEBMS.TBL_BILL_ARRCOMB_DTLID_UK ON "IEBMS".TBL_BILL_ARRCOMB_DTL(ARRCOMB_DTLID);

------------------------------------------------------tbl bill schedule dtl----------------------------------------------
CREATE INDEX IEBMS.TBL_BILL_SCHD_BKBPMP_INDX ON "IEBMS".TBL_BILL_SCHEDULE_DTL(BOOK_CODE, BILL_PERIOD, MON_PROC_FLAG);

CREATE INDEX IEBMS.TBL_BILL_SCHD_BPMP_INDX ON "IEBMS".TBL_BILL_SCHEDULE_DTL(BILL_PERIOD, MON_PROC_FLAG);

CREATE INDEX IEBMS.TBL_BILL_SCHD_BKBPBP_INDX ON "IEBMS".TBL_BILL_SCHEDULE_DTL(BOOK_CODE, BILL_PERIOD, BOOK_PROCESS_FLAG);

-----------------------------------------------------------------tbl bill collection hdr--------------------------------------------------------------------------

CREATE INDEX IEBMS.TBL_METER_READING_DTL_ID_INDX ON 
  "IEBMS".TBL_BILL(READING_ID) ; 

CREATE INDEX IEBMS.INDX_TBL_BILL_READING_DTL_ID ON 
  "IEBMS".TBL_BILL(BILL_NUM, READING_ID) ; 

CREATE INDEX IEBMS.TBL_BILL_CIBPBUST_INDX ON 
  "IEBMS".TBL_BILL(CUST_ID, BILL_PERIOD, BILLED_UNIT_TTL, TARIFF_CODE, TARIFF_GRP_CODE, G_SD_NAME_B) ; 

CREATE INDEX IEBMS.TBL_BILL_CIBPRBUT_INDX ON 
  "IEBMS".TBL_BILL(CUST_ID, BILL_PERIOD, REBATE_ACTSALES_AMT, TARIFF_CODE) ; 

CREATE INDEX IEBMS.TBL_BILL_CIBPBUT_INDX ON 
  "IEBMS".TBL_BILL(CUST_ID, BILL_PERIOD, BILLED_UNIT_TTL, TARIFF_CODE, TARIFF_GRP_CODE) ; 

CREATE INDEX IEBMS.TBL_BILL_LDGR_INDX ON 
  "IEBMS".TBL_BILL(BILL_ISSUE_DATE, BILL_LPC1_DATE, BILL_LPC2_DATE, BILL_DISCON_DATE, CUST_ID, BILL_PERIOD) ; 

CREATE INDEX IEBMS.TBL_BILL_BNRC_INDX ON 
  "IEBMS".TBL_BILL(BILL_NUM, REC_STATUS) ; 

CREATE INDEX IEBMS.TBL_BILL_BPRC_INDX ON 
  "IEBMS".TBL_BILL(BILL_PERIOD, REC_STATUS) ; 

CREATE INDEX IEBMS.TBL_BILL_BPBTRC_INDX ON 
  "IEBMS".TBL_BILL(BILL_PERIOD, BILL_TYPE, REC_STATUS) ; 

CREATE INDEX IEBMS.TBL_BILL_BNCIBPRC_INDX ON 
  "IEBMS".TBL_BILL(BILL_NUM, CUST_ID, BILL_PERIOD, REC_STATUS) ; 

CREATE INDEX IEBMS.TBL_BILL_LDGR_F_INDX ON 
  "IEBMS".TBL_BILL(BILL_NUM, BILL_ISSUE_DATE, BILL_LPC1_DATE, BILL_LPC2_DATE, BILL_DISCON_DATE, CUST_ID, BILL_PERIOD) ; 

CREATE INDEX IEBMS.TBL_BILL_BILLSHEET_INDX ON 
  "IEBMS".TBL_BILL(BILL_ISSUE_DATE, BILL_LPC1_DATE, BILL_LPC2_DATE, BILL_DISCON_DATE, BILL_PERIOD, BOOK_CODE, BILL_TYPE) ; 

CREATE INDEX IEBMS.TBL_BILL_BPTG_INDX ON 
  "IEBMS".TBL_BILL(BILL_PERIOD, TARIFF_GRP_CODE) ; 

CREATE INDEX IEBMS.TBL_BILL_CBID_INDX ON 
  "IEBMS".TBL_BILL(CHARGE_BASE_ID) ; 

CREATE INDEX IEBMS.TBL_BILL_SMS_BILLPRINT_INDX ON 
  "IEBMS".TBL_BILL(BILL_NUM, BILL_PERIOD, BILL_ISSUE_DATE) ; 

CREATE INDEX IEBMS.TBL_BILL_BP_BILLNUM_UK ON 
  "IEBMS".TBL_BILL(BOOK_CODE, BILL_PERIOD, BILL_NUM) ; 

CREATE INDEX IEBMS.TBL_BILL_CUST_ID__UK ON 
  "IEBMS".TBL_BILL(CUST_ID, BILL_PERIOD) ; 

CREATE INDEX IEBMS.TBL_CUSTOMER_METER_CUST_ID_UK ON 
  "IEBMS".TBL_BILL(CUST_ID) ; 

CREATE INDEX IEBMS.TBL_BILL_BP_ACBILL_NUM_UK ON 
  "IEBMS".TBL_BILL(BOOK_CODE, BILL_PERIOD, ACCOUNT_NUM, BILL_NUM) ; 

CREATE INDEX IEBMS.TBL_BILL_PRINT_UK ON 
  "IEBMS".TBL_BILL(BILL_ISSUE_DATE, BILL_LPC1_DATE, BILL_LPC2_DATE, BILL_DISCON_DATE, BOOK_CODE, BILL_PERIOD, ACCOUNT_NUM, BILL_NUM) ; 

CREATE INDEX IEBMS.TBL_BILL_MONSUM_INDX ON 
  "IEBMS".TBL_BILL(BOOK_CODE, TARIFF_CODE, BILL_PERIOD, REC_STATUS) ; 

CREATE INDEX IEBMS.TBL_BILL_BP_BT_UK ON 
  "IEBMS".TBL_BILL(BILL_PERIOD, BILL_TYPE) ; 

CREATE INDEX IEBMS.TBL_BILL_MONSUM_PROC_INDX ON 
  "IEBMS".TBL_BILL(BILL_ISSUE_DATE, BILL_LPC1_DATE, BILL_LPC2_DATE, BILL_DISCON_DATE, BOOK_CODE, TARIFF_CODE, BILL_PERIOD, REC_STATUS) ; 

CREATE INDEX IEBMS.TBL_BILL_BNCI_INDX ON 
  "IEBMS".TBL_BILL(BILL_NUM, CUST_ID) ; 

CREATE INDEX IEBMS.TBL_BILL_PRINTDUE_INDX ON 
  "IEBMS".TBL_BILL(BILL_NUM, BILL_ISSUE_DATE, BILL_LPC1_DATE, BILL_LPC2_DATE, BILL_DISCON_DATE) ; 

CREATE INDEX IEBMS.TBL_CUSTOMER_METER_BKBP_INDX ON 
  "IEBMS".TBL_BILL(BOOK_CODE, BILL_PERIOD) ; 

CREATE INDEX IEBMS.TBL_BILL_BOOKEMPCODE_INDX ON 
  "IEBMS".TBL_BILL(BOOK_EMP_CODE) ; 

CREATE UNIQUE INDEX IEBMS.TBL_BILL_BILL_NUM_UK ON 
  "IEBMS".TBL_BILL(BILL_NUM) ; 

CREATE INDEX IEBMS.TBL_BILL_CI_BP_RC_UK ON 
  "IEBMS".TBL_BILL(CUST_ID, BILL_PERIOD, REC_STATUS) ; 

CREATE INDEX IEBMS.INDX_BILL_CREATE ON 
  "IEBMS".TBL_BILL(CREATE_DATE) ; 
===========================cust misc info==========================

CREATE INDEX IEBMS.CI_MOBILE_INDEX ON 
  "IEBMS".TBL_CUSTOMER_MISC_INFO(CUST_ID, MOBILE_NO_1) 
  TABLESPACE USERS PCTFREE 10  STORAGE(INITIAL 4194304 ) 
; 

commit;