----- 1
SELECT * FROM
(SELECT ROWNUM AS ID, ST.* FROM
(SELECT (SELECT OFFICE_REB_ID FROM TBL_OFFICE WHERE STATUS='A') AS REB_ID,(SELECT DESCR FROM TBL_OFFICE WHERE STATUS='A') AS OFFICE_NAME, 
C.CUST_ID, C.BOOK_CODE, C.ACCOUNT_NUM, C.CUSTOMER_NAME_B, C.MOBILE_NO_1, B.BILL_PERIOD, B.NET_BILL_AMT
FROM VW_CUSTOMER_FULL_INFO C 
LEFT JOIN TBL_BILL B ON C.CUST_ID=B.CUST_ID
WHERE B.BILL_PERIOD=202206
ORDER BY BOOK_CODE, ACCOUNT_NUM ASC)ST)FT
WHERE FT.ID<=50000

----- 2
SELECT * FROM
(SELECT ROWNUM AS ID, ST.* FROM
(SELECT (SELECT OFFICE_REB_ID FROM TBL_OFFICE WHERE STATUS='A') AS REB_ID,(SELECT DESCR FROM TBL_OFFICE WHERE STATUS='A') AS OFFICE_NAME, 
C.CUST_ID, C.BOOK_CODE, C.ACCOUNT_NUM, C.CUSTOMER_NAME_B, C.MOBILE_NO_1, B.BILL_PERIOD, B.NET_BILL_AMT
FROM VW_CUSTOMER_FULL_INFO C 
LEFT JOIN TBL_BILL B ON C.CUST_ID=B.CUST_ID
WHERE B.BILL_PERIOD=202206
ORDER BY BOOK_CODE, ACCOUNT_NUM ASC)ST)FT
WHERE FT.ID>50000 AND FT.ID<=100000

----- 3
SELECT * FROM
(SELECT ROWNUM AS ID, ST.* FROM
(SELECT (SELECT OFFICE_REB_ID FROM TBL_OFFICE WHERE STATUS='A') AS REB_ID,(SELECT DESCR FROM TBL_OFFICE WHERE STATUS='A') AS OFFICE_NAME, 
C.CUST_ID, C.BOOK_CODE, C.ACCOUNT_NUM, C.CUSTOMER_NAME_B, C.MOBILE_NO_1, B.BILL_PERIOD, B.NET_BILL_AMT
FROM VW_CUSTOMER_FULL_INFO C 
LEFT JOIN TBL_BILL B ON C.CUST_ID=B.CUST_ID
WHERE B.BILL_PERIOD=202206
ORDER BY BOOK_CODE, ACCOUNT_NUM ASC)ST)FT
WHERE FT.ID>100000 AND FT.ID<=150000