UPDATE iebms.tbl_rates SET CHARGE_1=720,CHARGE_3=1920 
WHERE   EFF_BILL_PERIOD=202402 AND tariff_charge_code=29
AND TARIFF_GRP_CODE IN (SELECT TARIFF_GRP_CODE FROM iebms.TBL_TARIFF_GROUP WHERE TENS_NAME='LT');

UPDATE iebms.tbl_rates SET CHARGE_1=12000,CHARGE_3=12000
WHERE   EFF_BILL_PERIOD=202402 AND tariff_charge_code=29
AND TARIFF_GRP_CODE IN (SELECT TARIFF_GRP_CODE FROM iebms.TBL_TARIFF_GROUP WHERE TENS_NAME IN ('MT','HT'));

UPDATE iebms.tbl_rates SET CHARGE_1=24000,CHARGE_3=24000
WHERE   EFF_BILL_PERIOD=202402 AND tariff_charge_code=29
AND TARIFF_GRP_CODE IN (SELECT TARIFF_GRP_CODE FROM iebms.TBL_TARIFF_GROUP WHERE TENS_NAME='EHT');
COMMIT;