drop INDEX IEBMS.TBL_BILL_ARRHDR_CPRC_INDX;

drop INDEX IEBMS.TBL_BILL_ARRHDR_CIBPDC_INDX;

drop INDEX IEBMS.TBL_BILL_ARRHDR_BP_BN_INDX;

drop INDEX IEBMS.TBL_BILL_ARRHDR_BPBA_INDX;

drop INDEX IEBMS.TBL_BILL_ARRHDR_CIBPABPDC_INDX;

drop INDEX IEBMS.TBL_BILL_ARRHDR_BP_INDX;

drop INDEX IEBMS.TBL_BILL_ARRHDR_CERT_INDX;

drop INDEX IEBMS.TBL_BILL_ARRHDR_BILL_NUM_INDX;

drop INDEX IEBMS.TBL_BILL_ARRHDR_ARRBILLID_INDX;

drop INDEX IEBMS.TBL_BILL_ARRHDR_CIBP_UK;