
UPDATE TBL_CUSTOMER_INTERFACE SET MBR_SHIP_SR_NO = ELAKA_CODE || '-' || (LPAD(ROWNUM,6,0)) 
WHERE ELAKA_CODE='01' AND MBR_SHIP_SR_NO IS NULL

============================================================================
select MBR_SHIP_SR_NO from tbl_customer_interface where elaka_code='01'

UPDATE TBL_CUSTOMER_INTERFACE SET MBR_SHIP_SR_NO = NULL
WHERE ELAKA_CODE='01'


UPDATE TBL_CUSTOMER_INTERFACE SET MBR_SHIP_SR_NO = ELAKA_CODE || '-' || (ROWNUM+27189) 
WHERE ELAKA_CODE='01' AND MBR_SHIP_SR_NO IS NULL


UPDATE TBL_CUSTOMER_INTERFACE SET MBR_SHIP_SR_NO = ELAKA_CODE || (LPAD(ROWNUM+6564,6,0)) 
WHERE ELAKA_CODE='06' AND MBR_SHIP_SR_NO IS NULL


UPDATE TBL_CUSTOMER_INTERFACE SET ELAKA_CODE='06' 
WHERE g_union_code='06' 