SELECT cust_id,COUNT(reading_dtlid) AS rd FROM TBL_METER_READING_DTL WHERE book_code=097 AND bill_period=202410 GROUP BY cust_id

SELECT cust_id,COUNT(reading_dtlid) AS rd FROM TBL_METER_READING_DTL WHERE book_code=196 
AND bill_period=202410 GROUP BY cust_id HAVING COUNT(reading_dtlid)=1

SELECT book_code,account_num, BILL_PERIOD, PREV_READING, 
CUR_READING,CREATE_DATE, CREATE_BY, UPDATE_DATE, UPDATE_BY, REC_STATUS
FROM TBL_METER_READING_DTL WHERE cust_id IN (27112596,76177344,27321119) AND bill_period=202410

