 SELECT MAX(TO_NUMBER(trim(APP_TRACK_NO))) FROM iebms.TBL_ONLINE_APP WHERE APP_TRACK_NO NOT IN (
 SELECT APP_TRACK_NO FROM (
 SELECT LENGTH(TRANSLATE(trim(APP_TRACK_NO),' 0123456789',' ')),APP_TRACK_NO FROM iebms.TBL_ONLINE_APP 
 WHERE LENGTH(TRANSLATE(trim(APP_TRACK_NO),' 0123456789',' '))>0)
 
 ) AND APP_DATE>'30-Apr-2019' 
 
 
SELECT *  FROM iebms.TBL_ONLINE_APP1
WHERE APP_TRACK_NO NOT IN (
SELECT APP_TRACK_NO  FROM dfa
)
;
ALTER TABLE iebms.TBL_ONLINE_APP ADD tk NUMBER  
UPDATE iebms.TBL_ONLINE_APP SET tk= TO_NUMBER(APP_TRACK_NO)
WHERE  REGEXP_LIKE(APP_TRACK_NO, '[^0-9]')

CREATE TABLE iebms.TBL_ONLINE_APP
AS
CREATE TABLE sd
AS

SELECT * FROM iebms.TBL_ONLINE_APP WHERE APP_TRACK_NO NOT IN ()
SELECT * FROM IEBMS.TBL_ONLINE_APP WHERE   REGEXP_LIKE(APP_TRACK_NO, '[^0-9]')

CREATE TABLE big_Ap_no
AS

SELECT * FROM IEBMS.TBL_ONLINE_APP1 WHERE  REGEXP_LIKE(APP_TRACK_NO, '[[:alpha:]]')

DELETE FROM iebms.TBL_ONLINE_APP WHERE LENGTH(APP_TRACK_NO)>10

UPDATE iebms.TBL_ONLINE_APP  SET  APP_TRACK_NO=trim(APP_TRACK_NO)



CREATE TABLE dd
 AS
SELECT APP_TRACK_NO FROM (
 SELECT LENGTH(TRANSLATE(trim(APP_TRACK_NO),' 0123456789',' ')),APP_TRACK_NO FROM iebms.TBL_ONLINE_APP 
 WHERE LENGTH(TRANSLATE(trim(APP_TRACK_NO),' 0123456789',' '))>0
 
 )
 
 SELECT * FROM iebms.TBL_ONLINE_APP WHERE 


APP_TRACK_NO NOT IN (

SELECT APP_TRACK_NO FROM dd WHERE APP_TRACK_NO<>'2'
 
 
 ) AND APP_DATE>'30-Apr-2019' 
 
  DELETE FROM iebms.TBL_ONLINE_APP WHERE APP_ID IN 
( SELECT a FROM (
 SELECT MIN(APP_ID) AS a,APP_TRACK_NO FROM IEBMS.TBL_ONLINE_APP GROUP BY APP_TRACK_NO HAVING COUNT(APP_TRACK_NO)>1
 ))




===================================== my query for triming data =========================
 SELECT *
FROM your_table
WHERE REGEXP_LIKE(to_number(or_num), '[^0-9]');


SELECT * FROM TBL_OFFICE_COLLECTION_MST
WHERE coll_type=4 AND REGEXP_LIKE(TO_NUMBER(or_num), '[^0-9]');

SELECT *
FROM TBL_OFFICE_COLLECTION_MST
WHERE coll_type=4 AND NOT REGEXP_LIKE(or_no, '^-?[0-9]+$');

UPDATE TBL_OFFICE_COLLECTION_MST
SET or_no = REGEXP_REPLACE(or_no, '[^0-9-]', '')
WHERE NOT REGEXP_LIKE(or_no, '^-?[0-9]+$');