
---Office Reciept (OR/CD)
CREATE  TABLE IEBMS.OFFICERCPT_P2I 
AS
SELECT 0 iORNUM,0 iCUST_ID,OB.*,OD.ACC_NO,OD.OR_BILL_AMT,ACC_DESC, ACC_DESC_ENG, OR_PAID_AMT, OR_PAID_YN, CASH_CHECK_YN, CASH_REF_BY, CASH_REF_DATE
FROM PMS.OR_BILL OB,PMS.OR_BILL_DETAIL OD WHERE OB.BILLNO=OD.BILLNO AND OB.OR_BILL_DATE IS NOT NULL



UPDATE IEBMS.OFFICERCPT_P2I o SET iCUST_ID=(SELECT cust_id FROM iebms.tbl_customer_interface c WHERE c.BOOK_CODE=LPAD(o.BOOK_NO,3,'0') AND C.ACCOUNT_NUM=o.ACNO)
WHERE APPN IS NOT NULL

INSERT INTO TBL_ONLINE_APP(APP_ID, 
APP_DATE, 						  APP_TRACK_NO,    		   APP_OWNER_NAME, 							 APP_FATHER, 
  APP_HOLDING_NO_PRS, 			  APP_POST_OFFICE_PRS_TXT, APP_DISTRICT_PRS_TXT, 					 APP_SUB_DISTRICT_PRS_TXT, 
  APP_UNION_PRS_TXT, 			  APP_VILLAGE_PRS_TXT) 
SELECT SEQ_TBL_ONLINE_APP.NEXTVAL, S.* FROM
(
SELECT  DISTINCT APP_DATE , 	 BILLNO  ,			   	   NAME APP_OWNER_NAME,  				 F_H_NAME APP_FATHER,
PRE_ADDR , 	 	 				 P_OFFICE,				   ZELA, 								 THANA, 
UNIONX,  						 VILLAGE				
FROM IEBMS.OFFICERCPT_P2I  WHERE APPN IS NULL AND CONS_TYPE<>'IN' AND iCUST_ID=0
) S






INSERT INTO TBL_OFFICE_RECIEPT(OR_ID, 	 	  OR_DATE, 			  	  CREATE_BY,  				 UPDATE_BY, 
OR_DESCR, 									  CUST_ID, BOOK_CODE, 	  ACCOUNT_NUM,  			 REC_STATUS,
 OR_AMOUNT_TTL, APP_TRACK_NO, OR_TYPE, OR_TITLE, APP_TRK, 
 CONS_NAME, CONS_ADDRESS)
SELECT -BILLNO,			 	  		    OR_BILL_DATE OR_DATE, 		  ENTRY_BY CREATE_BY,  		 DESC_MADE_BY, 
MAX(ACC_DESC_ENG) OR_DESCR, 				iCUST_ID,BOOK_NO BOOK_CODE,ACNO ACCOUNT_NUM,		 8 REC_STATUS,
 SUM(OR_BILL_AMT) ,APPN , (CASE WHEN OR_TYPE ='D' THEN 6 ELSE 4 END ),MAX(ACC_DESC) OR_TITLE, BILLNO,  
 NAME, NVL(PRE_ADDR,'') || ' ' || VILLAGE ||  ' ' || UNIONX ||  ' ' || THANA ||   ' ' || ZELA  ||  ' ' ||P_OFFICE  
  FROM OFFICERCPT_P2I
 GROUP BY -BILLNO, OR_BILL_DATE , ENTRY_BY ,  DESC_MADE_BY, iCUST_ID,BOOK_NO ,ACNO ,
(CASE WHEN OR_TYPE ='D' THEN 6 ELSE 4 END ), BILLNO,  
 NAME, NVL(PRE_ADDR,'') || ' ' || VILLAGE ||  ' ' || UNIONX ||  ' ' || THANA ||   ' ' || ZELA  ||  ' ' ||P_OFFICE 
 
 
  INSERT INTO TBL_OFFICE_RECIEPT_DTL(OR_DTL_ID, OR_ID, OFFICE_ACC_CODE, OR_AMOUNT, DTL_DESCR)
SELECT SEQ_TBL_OFFICE_RECIEPT_DTL.NEXTVAL,-BILLNO,  ACC_NO,OR_BILL_AMT ,ACC_DESC_ENG FROM  OFFICERCPT_P2I


UPDATE IEBMS.TBL_OFFICE_RECIEPT_DTL SET OFFICE_ACC_CODE='225.10' WHERE OFFICE_ACC_CODE='225.1';
 
---Office Collection OR CD
ALTER TABLE  TBL_OFFICE_COLLECTION  ADD OR_NUMBER VARCHAR(100) ;
ALTER TABLE  TBL_OFFICE_COLLECTION  ADD APPNO VARCHAR(100) ;
ALTER TABLE  TBL_OFFICE_COLLECTION  ADD OR_TYPE NUMBER ;
CREATE INDEX IDXOR ON  TBL_OFFICE_COLLECTION(  OR_NUMBER,OR_TYPE,APPNO );
CREATE INDEX IDXORM ON  TBL_OFFICE_COLLECTION_MST(  OR_NO,COLL_TYPE,APPLICATION_NUM );
COMMIT;



----OR/CD COLLECTION
CREATE TABLE IEBMS.OR_COLLECTION_P2I
AS
SELECT B.*,D.ACC_NO, D.ACC_DESC, D.ACC_DESC_ENG, D.OR_BILL_AMT, D.OR_PAID_AMT, D.OR_PAID_YN
FROM PMS.OR_COLL B, PMS.OR_COLL_DETAIL D WHERE 
B.OR_NO = D.OR_NO
AND B.OR_TYPE = D.OR_TYPE
AND B.BILLNO = D.BILLNO
AND B.OFFICE_CODE=D.OFFICE_CODE 



ALTER TABLE IEBMS.OR_COLLECTION_P2I ADD iCUSTID NUMBER

UPDATE IEBMS.OR_COLLECTION_P2I o 
SET iCUSTID=(SELECT cust_id FROM iebms.tbl_customer_interface c WHERE c.BOOK_CODE=LPAD(o.BOOK_NO,3,'0') AND C.ACCOUNT_NUM=o.ACNO)
WHERE APPN IS NOT NULL

DELETE FROM IEBMS.TBL_OFFICE_COLLECTION_MST WHERE create_by='DTO';


INSERT INTO  IEBMS.TBL_OFFICE_COLLECTION_MST(OFFM_COLL_ID,		 OFFICE_COLL_DATE,				OFFICE_CODE,			 ELAKA_CODE,			  BOOK_CODE,
 ACCOUNT_NUM, 												 CUST_ID,						COLL_POINT_CODE,
 OFFICE_COLL_AMT,											 REC_STATUS,					CREATE_BY,				 CREATE_DATE,
COLL_BILL_PERIOD,											 COLL_TYPE,						PAY_TYPE,				 COLL_SRC,	 			  POINT_TYPE,
OR_NO,														 APPLICATION_NUM,				SCROLL_NUM)

SELECT -OR_NO || BILLNO OR_NO,												 TRUNC(OR_COLL_DATE) OR_COLL_DATE,				'GP',						 0,						  LPAD(BOOK_NO,3,'0') ,
ACNO,  														 iCustID,					8,
SUM( OR_PAID_AMT) OR_PAID_AMT,											 'A',						'DTO',						 SYSDATE,
TO_CHAR(OR_COLL_DATE,'rrrrMM') ,						 (CASE WHEN OR_TYPE='D' THEN 6 ELSE 4 END) OR_TYPE,	 							'CSH',	 	 			 'U'					  ,1,
-BILLNO,													 BILLNO,				0
FROM IEBMS.OR_COLLECTION_P2I --WHERE  OR_NO=9994
GROUP BY OR_NO,BILLNO, TRUNC(OR_COLL_DATE) ,OR_TYPE,BOOK_NO,ACNO,iCustID,TO_CHAR(OR_COLL_DATE,'rrrrMM')

)

--SELECT OR_NO,OR_TYPE, SUM(OR_PAID_AMT),COUNT(OR_NO) FROM (   --WHERE  TRUNC(OR_COLL_DATE)='15-MAR-2018'
--GROUP BY OR_NO,OR_TYPE HAVING COUNT(OR_NO)>1




DELETE FROM IEBMS.TBL_OFFICE_COLLECTION WHERE create_by='DTO';

 INSERT INTO IEBMS.TBL_OFFICE_COLLECTION (OFFICE_COLL_ID, 	OFFICE_COLL_DATE, 	  OFFICE_ACCNO, 	   		  	   							OFFICE_CODE, 
 ELAKA_CODE,  			BOOK_CODE, 						ACCOUNT_NUM, 		  CUST_ID, 													COLL_POINT_CODE, 
 OFFICE_COLL_AMT, 		REC_STATUS, 					CREATE_BY, 			  CREATE_DATE, 												COLL_BILL_PERIOD, 
 OFFM_COLL_ID, 			BILLED_AMT, 					OR_NUMBER, 			  APPNO, 													OR_TYPE)
SELECT IEBMS.SEQ_TBL_OFFICE_COLLECTION.NEXTVAL, 				TRUNC(OR_COLL_DATE)	,		ACC_NO			,				'GP',	
0,						LPAD(BOOK_NO,3,'0') ,			ACNO,  					iCustID,												1,
OR_PAID_AMT,			'A',							'DTO',					SYSDATE,												TO_CHAR(OR_COLL_DATE,'rrrrMM'),								 
-OR_NO || BILLNO,				OR_BILL_AMT						,-BILLNO,				APPN,													(CASE WHEN OR_TYPE='D' THEN 6 ELSE 4 END)
FROM IEBMS.OR_COLLECTION_P2I



UPDATE IEBMS.TBL_OFFICE_COLLECTION SET OFFICE_ACCNO='225.10' WHERE OFFICE_ACCNO='225.1';
UPDATE IEBMS.TBL_OFFICE_COLLECTION SET OFFICE_ACCNO='108.20' WHERE OFFICE_ACCNO='108.2';





--SELECT PRIMARY_APP_NO,ORNO FROM TBL_WIRING_INSPECTION W,
--(SELECT APPN,MAX(BILLNO) AS ORNO FROM IEBMS.OR_COLLECTION_P2I WHERE APPN IS NOT NULL AND ACC_NO=225.1 GROUP BY appn) CL
--WHERE W.PRIMARY_APP_NO=CL.APPN




UPDATE  TBL_WIRING_INSPECTION W
SET W.APP_TRK=(SELECT ORNO FROM (SELECT APPN,MAX(BILLNO) AS ORNO FROM IEBMS.OR_COLLECTION_P2I WHERE APPN IS NOT NULL AND ACC_NO=225.1 GROUP BY appn) CL
WHERE W.PRIMARY_APP_NO=CL.APPN)
WHERE W.APP_TRK IS NULL OR W.APP_TRK=''


INSERT INTO TBL_ONLINE_APP(APP_ID, 
APP_DATE, 						  APP_TRACK_NO,    		   APP_OWNER_NAME, 							 APP_FATHER, 
  APP_HOLDING_NO_PRS, 			  APP_POST_OFFICE_PRS_TXT, APP_DISTRICT_PRS_TXT, 					 APP_SUB_DISTRICT_PRS_TXT, 
  APP_UNION_PRS_TXT, 			  APP_VILLAGE_PRS_TXT) 
SELECT SEQ_TBL_ONLINE_APP.NEXTVAL, S.* FROM
(
SELECT  DISTINCT APPDATE , 	  APP_TRK  ,			   	   NAME,  				 F_H_NAME ,
PRE_ADDR , 	 	 				 P_OFFICE,				   ZELA, 								 THANA, 
UNIONX,  						 VILLAGE				
FROM (
SELECT C.* , W.APP_TRK FROM tbl_wiring_inspection W,PMS.CONS_IEBMS C  WHERE W.PRIMARY_APP_NO=C.APPN AND W.app_trk IS NOT NULL
AND W.APP_TRK  NOT IN (SELECT APP_TRACK_NO FROM TBL_ONLINE_APP))
) S


UPDATE TBL_SUB_STATION SET STATION_NAME_B=STATION_NAME
UPDATE TBL_SUB_STATION S SET S.STATION_NAME=(SELECT ST FROM 
(SELECT SUB_STATION,MAX(E_SUB_STATION) ST FROM pms.CONS_IEBMS WHERE SUB_STATION IS NOT NULL AND E_SUB_STATION IS NOT NULL GROUP BY SUB_STATION) SS
 WHERE S.STATION_NAME_B=SS.SUB_STATION)
 WHERE S.STATION_NAME_B IS NOT NULL AND S.STATION_NAME IS NOT NULL
 
 

 UPDATE TBL_FEEDER SET FEEDER_DESCR_B=FEEDER_DESCR
UPDATE TBL_FEEDER  S SET S.FEEDER_DESCR=(SELECT ST FROM 
(SELECT FEDER,MAX(E_FEDER) ST FROM pms.CONS_IEBMS WHERE FEDER IS NOT NULL AND E_FEDER IS NOT NULL GROUP BY FEDER) SS
 WHERE S.FEEDER_DESCR_B=SS.FEDER)
 WHERE S.FEEDER_DESCR_B IS NOT NULL AND S.FEEDER_DESCR IS NOT NULL

--INSERT INTO   TBL_FEEDER (FEEDER_CODE, FEEDER_DESCR_B,OFFICE_CODE)
  --SELECT FEDER_ID, FEDER,'Gp' FROM
  --pms.FEEDER_IEBMS
  


