ALTER TABLE TBL_BILL_ARREAR_HDR RENAME COLUMN ARR_BILL_HRDID TO ARR_BILL_HDRID;
COMMIT;


ALTER TABLE TBL_BILL_COLLECTION_HDR RENAME COLUMN READING_DTLLD TO READING_DTLID;
COMMIT;



ALTER TABLE TBL_BILL_COLLECTION_HDR RENAME COLUMN cool_num TO coll_num;
COMMIT;












ALTER TABLE TBL_BILL_ARREAR_HDR RENAME COLUMN ARR_BILL_HRDID TO ARR_BILL_HDRID;
COMMIT;