CREATE TABLE SMS.TBL_SMS_DOWNLOAD (
  TRANSID               NUMBER (30)   NOT NULL,
  TRANSDATE             DATE,
  BILLNO                NUMBER (30),
  BOOKNO                VARCHAR2 (5),
  ACCOUNTNO             NUMBER,
  BILLMONTH             NUMBER,
  BILLYEAR              NUMBER,
  ISSUEDATE             DATE,
  DUEDATE               DATE,
  BILLAMOUNTWITHOUTLPC  NUMBER,
  LPCDATE               DATE,
  BILLAMOUNTWITHLPC     NUMBER,
  BILLSTATUS            VARCHAR2 (20),
  PAYMENTDATE           DATE,
  AMOUNTPAID            NUMBER,
  METERNO               VARCHAR2 (20),
  PREVIOUSMETERREADING  VARCHAR2 (20),
  PRESENTMETERREADING   VARCHAR2 (20),
  RESPONSECODE          VARCHAR2 (20),
  RESPONSEDESC          VARCHAR2 (200),
  RECORDFETCHED         VARCHAR2 (20),
  ERR                   VARCHAR2 (2),
  DOWNLOADBY            VARCHAR2 (1000),
  SLNO                  NUMBER,
  STATUS                NUMBER,
  BILL_NUM              NUMBER,
  BILL_LPC_DATE         DATE,
  BILLED_AMT            NUMBER,
  BILLED_LPC            NUMBER,
  TO_BE_PAID            NUMBER,
  COLL_PAID             NUMBER,
  PRIMARY KEY ( TRANSID )
    USING INDEX
     TABLESPACE USERS PCTFREE 10
     STORAGE ( INITIAL 786432 ))
   TABLESPACE USERS
   PCTFREE 10
   INITRANS 1
   MAXTRANS 255
  STORAGE (
   INITIAL 7340032
   MINEXTENTS 1
   MAXEXTENTS 2147483645
 )
   NOCACHE;


CREATE INDEX SMS.TBL_SMS_DOWNLOAD_INDX ON
  "SMS".TBL_SMS_DOWNLOAD(BILLNO, PAYMENTDATE)
  TABLESPACE USERS PCTFREE 10  STORAGE(INITIAL 2097152 )
;




CREATE TABLE  SMS.TBL_SMS_UPLOAD (
  TRANSID               NUMBER (30)   NOT NULL,
  TRANSDATE             DATE,
  BILLNO                NUMBER (30),
  BOOKNO                VARCHAR2 (5),
  ACCOUNTNO             NUMBER,
  BILLMONTH             NUMBER,
  BILLYEAR              NUMBER,
  ISSUEDATE             DATE,
  DUEDATE               DATE,
  BILLAMOUNTWITHOUTLPC  NUMBER,
  LPCDATE               DATE,
  BILLAMOUNTWITHLPC     NUMBER,
  METERNO               VARCHAR2 (20),
  PREVIOUSMETERREADING  VARCHAR2 (20),
  PRESENTMETERREADING   VARCHAR2 (20),
  SUCCESS               NUMBER,
  ERRORCODE             VARCHAR2 (20),
  ERRORDESC             VARCHAR2 (255),
  BILLTYPE              NUMBER,
  PRIMARY KEY ( TRANSID )
    USING INDEX
     TABLESPACE USERS PCTFREE 10
     STORAGE ( INITIAL 8388608 ))
   TABLESPACE USERS
   PCTFREE 10
   INITRANS 1
   MAXTRANS 255
  STORAGE (
   INITIAL 62914560
   MINEXTENTS 1
   MAXEXTENTS 2147483645
 )
   NOCACHE;


CREATE INDEX SMS.TBL_SMS_UPLOAD_INDX ON
  "SMS".TBL_SMS_UPLOAD(BILLNO, SUCCESS, BILLTYPE)
  TABLESPACE USERS PCTFREE 10  STORAGE(INITIAL 23068672 )
;


CREATE TABLE SMS.TBL_SMS_FIELD (
  FIELD_ID              NUMBER        NOT NULL,
  BILLNO                VARCHAR2 (300),
  BOOKNO                VARCHAR2 (100),
  ACCOUNTNO             VARCHAR2 (100),
  BILLPERIOD            VARCHAR2 (100),
  CURRENTPERIOD         VARCHAR2 (255),
  BILLMONTH             VARCHAR2 (100),
  BILLYEAR              VARCHAR2 (100),
  ISSUEDATE             VARCHAR2 (100),
  DUEDATE               VARCHAR2 (100),
  BILLAMOUNTWITHOUTLPC  VARCHAR2 (100),
  LPCDATE               VARCHAR2 (100),
  BILLAMOUNTWITHLPC     VARCHAR2 (100),
  METERNO               VARCHAR2 (100),
  PREVIOUSMETERREADING  VARCHAR2 (100),
  PRESENTMETERREADING   VARCHAR2 (100),
  USERNAME              VARCHAR2 (100),
  PASSWORD              VARCHAR2 (100),
  URL                   VARCHAR2 (255),
  TABLENAME             VARCHAR2 (100),
  PRIMARY KEY ( FIELD_ID )
    USING INDEX
     TABLESPACE USERS PCTFREE 10
     STORAGE ( INITIAL 65536 ))
   TABLESPACE USERS
   PCTFREE 10
   INITRANS 1
   MAXTRANS 255
  STORAGE (
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
 )
   NOCACHE;


INSERT INTO SMS.TBL_SMS_FIELD ( FIELD_ID, BILLNO, BOOKNO, ACCOUNTNO, BILLPERIOD, CURRENTPERIOD,
BILLMONTH, BILLYEAR, ISSUEDATE, DUEDATE, BILLAMOUNTWITHOUTLPC, LPCDATE, BILLAMOUNTWITHLPC, METERNO,
PREVIOUSMETERREADING, PRESENTMETERREADING, USERNAME, PASSWORD, URL,
TABLENAME ) VALUES (
1, 'BILL_NUM', 'BOOK_CODE', 'ACCOUNT_NUM', 'BILL_PERIOD', 'select current_period from iebms.tbl_office where status=''A'''
, 'Substring(BillPeriod, 4,2)', 'Substring(BillPeriod, 0,4)', 'BILL_ISSUE_DATE', 'BILL_DISCON_DATE'
, 'TOTAL_BILL_AMT', 'BILL_LPC1_DATE', 'LPC_1_AMT+TOTAL_BILL_AMT', 'METER_NUM', 'PREV_READING_OFPK'
, 'CUR_READING_OFPK', 'apitest', 'apitest', 'https://reb.teletalk.com.bd/dataexchangeapi.php'
, 'TBL_BILL');
COMMIT;




