connect iebms/iebms@iebms;
host imp iebms/iebms@iebms FILE=DB.DMP GRANTS=Y IGNORE=Y FROMUSER=(IEBMS,ONE_POINT,DMS,PROCIS,ITI,REB_MIS,STAR_CASH,UISC,SMS) TOUSER=(IEBMS,ONE_POINT,DMS,PROCIS,ITI,REB_MIS,STAR_CASH,UISC,SMS);
