--All list insert into this table-----
CREATE TABLE TBL_ONEPOINT_CMP_NEW ( 
  CMP_ID      NUMBER        NOT NULL, 
  CMP_NAME    VARCHAR2 (200), 
  CMP_NAME_B  VARCHAR2 (300), 
   PRIMARY KEY ( CMP_ID ) ) 
  
  
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
22, NULL, 'we`y¨s wej ms‡kvab cÖ‡qvRb'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
1, NULL, 'bZzb ms‡hvM Ges †jvW cwieZ©‡bi Av‡e`b wd (cÖwZwU wgUv‡ii Rb¨)'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
2, NULL, 'A¯''vqx ms‡hvM Gi Av‡e`b wd'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
3, NULL, 'e‡Kqvi Kvi‡Y ms‡hvM wew"Qbœ/cyYt ms‡hvM (wWwm/Aviwm) wd'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
4, NULL, 'MÖvn‡Ki Aby‡iv‡a ms‡hvM wew"Qbœ/cyYt ms‡hvM (wWwm/Aviwm) wd'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
5, NULL, 'MÖvn‡Ki Aby‡iv‡a wgUvi cixÿv wd'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
6, NULL, 'MÖvn‡Ki Aby‡iv‡a MÖvnK Avw½bvq wgUvi cwi`k©b wd'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
7, NULL, 'MÖvn‡Ki Aby‡iv‡a wgUvi/wgUvwis BDwbU ¯''vcb cwieZ©b/ ¯''vbvšÍi wd'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
8, NULL, 'MÖvn‡Ki Aby‡iv‡a mvwf©©m Wªc K¨vej (mvwf©m wµgwcU/K¨v¤úmn/†givgZ/cwieZ©b/¯''vbvšÍi wd) '); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
9, NULL, 'MÖvn‡Ki Aby‡iv‡a mieivn/ Pzw³ ms‡kvab wd'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
10, NULL, 'mvwf©m Wªc Zv‡ii g~j¨/ cÖwZ dzU'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
11, NULL, 'wgUv‡ii gyj¨'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
12, NULL, 'm‡K‡Ui gyj¨'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
15, NULL, 'jvBb / †cvj ¯''vbvšÍi wd'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
16, NULL, 'wjM¨vj †bvwUk / DwKj †bvwUk'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
17, NULL, 'MÖvn‡Ki Aby‡iv‡a wcÖ-‡cBW wgUvi KvW© wi-Bmy¨ wd'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
18, NULL, 'MÖvn‡Ki Aby‡iv‡a Riƒix cÖ‡qvR‡b WªcAvDU wcDR KvU-AvDU mn UªvÝdigvi fvov wd'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
19, NULL, 'MÖvn‡Ki Aby‡iv‡a UªvÝdigv‡ii †Zj cixÿv PvR©'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
20, NULL, 'UªvÝdigv‡ii g~j¨/‡giwgZ'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
21, NULL, 'UªvÝdigv‡ii DVv‡bv / bvgv‡bv wd'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
999, NULL, 'Ab¨vb¨ '); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
14, NULL, 'bvg cwieZ©b wd'); 
INSERT INTO TBL_ONEPOINT_CMP_NEW ( CMP_ID, CMP_NAME, CMP_NAME_B ) VALUES ( 
13, NULL, 'UªvÝdigv‡ii DVv‡bv / bvgv‡bv wd'); 
COMMIT;

CREATE TABLE iebms.TBL_OP_SERVICE_DTL (
  SERV_DTLID          NUMBER        NOT NULL,
  SERV_HDRID          NUMBER,
  COMPLAIN_TYPE_CODE  INTEGER       NOT NULL,
  DESCR               VARCHAR2 (500),
  ACTION              VARCHAR2 (500),
  ACTION_DATE         DATE,
  ACTION_BY           INTEGER,
  REC_STATUS          VARCHAR2 (1)  NOT NULL,
  CONSTRAINT TBL_OP_SERVICE_DTLID_PK
  PRIMARY KEY ( SERV_DTLID ) );
  
  
  
CREATE TABLE iebms.TBL_ONEPOINT_SERVICE_DTL (
  OP_SERV_DTLID        NUMBER        NOT NULL,
  OP_SERVID            NUMBER,
  COMPLAIN_TYPE_CODE   INTEGER       NOT NULL,
  COMPLAIN_DESCR_B     VARCHAR2 (200),
  COMPLAIN_DECISION_B  VARCHAR2 (200),
  PRIMARY KEY ( OP_SERV_DTLID ) );
  
  CREATE TABLE TBL_ONEPOINT_SERVICE (
  OP_SERVID         NUMBER        NOT NULL,
  SERVICE_DATE      DATE          NOT NULL,
  CUST_ID           NUMBER,
  OFFICE_CODE       VARCHAR2 (2)  NOT NULL,
  ELAKA_CODE        VARCHAR2 (2),
  BOOK_CODE         VARCHAR2 (5),
  ACCOUNT_NUM       NUMBER,
  CUSTOMER_NAME_B   VARCHAR2 (50),
  F_H_NAME_B        VARCHAR2 (50),
  G_DIST_CODE       NUMBER,
  G_SD_CODE         NUMBER,
  G_UNION_CODE      NUMBER,
  G_VILL_CODE       NUMBER,
  COMPLAINT_NAME_B  VARCHAR2 (50),
  EMP_CODE          INTEGER,
  PAYTO_TYPE_CODE   INTEGER,
  FOR_REWIRING      VARCHAR2 (1),
  SERVICE_TIME      DATE,
  REC_STATUS        VARCHAR2 (1),
  CREATE_BY         VARCHAR2 (10),
  CREATE_DATE       DATE,
  UPDATE_BY         VARCHAR2 (10),
  UPDATE_DATE       DATE,
  PRIMARY KEY ( OP_SERVID ));
  
  DROP TABLE IEBMS.TBL_ONEPOINT_CMP_CHARGES;
  
  CREATE TABLE IEBMS.TBL_ONEPOINT_CMP_CHARGES ( 
  CMP_ID           NUMBER        NOT NULL, 
  CHARGE_ACC       VARCHAR(30), 
  CHARGE           NUMBER (10,2),
  ACC_CODE         VARCHAR(10),
  PHASE            NUMBER,
  TARIFF_GRP_CODE  NUMBER,
  ACC_HEAD         VARCHAR(10) ,
  VAT              NUMBER,
  O_TYPE           VARCHAR2 (30));
  
 
 --charges Insert into This Table-------------
--ALTER TABLE TBL_ONEPOINT_CMP_CHARGES MODIFY CHARGE_ACC VARCHAR(30)
--ALTER TABLE TBL_ONEPOINT_CMP_CHARGES ADD TARIFF_GRP_CODE NUMBER
--ALTER TABLE TBL_ONEPOINT_CMP_CHARGES ADD PHASE NUMBER
--ALTER TABLE TBL_ONEPOINT_CMP_CHARGES ADD ACC_HEAD VARCHAR(10)
--ALTER TABLE TBL_ONEPOINT_CMP_CHARGES ADD VAT NUMBER
--ALTER TABLE TBL_ONEPOINT_CMP_CHARGES ADD O_TYPE       VARCHAR2 (30)
--ALTER TABLE TBL_ONEPOINT_CMP_CHARGES DROP CONSTRAINT TBL_ONEPOINT_CMP_CHARGES_PK



ALTER TABLE TBL_ONEPOINT_CMP_CHARGES ADD CONSTRAINT TBL_ONEPOINT_CMP_CHARGES_PK PRIMARY KEY (CMP_ID, CHARGE_ACC, TARIFF_GRP_CODE,PHASE,O_TYPE);

ALTER TABLE TBL_ONEPOINT_SERVICE_DTL ADD CHARGE_ACC VARCHAR(30);
ALTER TABLE TBL_ONEPOINT_SERVICE_DTL ADD CHARGE NUMBER;
ALTER TABLE TBL_ONEPOINT_SERVICE_DTL ADD VAT NUMBER;
ALTER TABLE TBL_ONEPOINT_SERVICE_DTL ADD ACC_HEAD VARCHAR(10);
ALTER TABLE TBL_ONEPOINT_SERVICE_DTL ADD OTHER_DESC VARCHAR(200);
ALTER TABLE TBL_ONEPOINT_SERVICE_DTL ADD TARIFF_GRP_CODE NUMBER;
ALTER TABLE TBL_ONEPOINT_SERVICE_DTL ADD PHASE NUMBER;
ALTER TABLE TBL_ONEPOINT_SERVICE_DTL ADD O_TYPE VARCHAR(50);
ALTER TABLE TBL_ONEPOINT_SERVICE_DTL ADD CREATE_BY VARCHAR(50);
ALTER TABLE TBL_ONEPOINT_SERVICE_DTL ADD CREATE_DATE DATE;
ALTER TABLE TBL_ONEPOINT_SERVICE_DTL MODIFY COMPLAIN_TYPE_CODE NUMBER;
ALTER TABLE TBL_ONEPOINT ADD TOTAL_AMT NUMBER;
ALTER TABLE TBL_ONEPOINT ADD VAT NUMBER;


COMMIT;


INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 6000, NULL, 0, 24, '241.35', 900, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 6000, NULL, 0, 25, '241.35', 900, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 6000, NULL, 0, 26, '241.35', 900, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 6000, NULL, 0, 27, '241.35', 900, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 6000, NULL, 0, 31, '241.35', 900, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 6000, NULL, 0, 32, '241.35', 900, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 6000, NULL, 0, 33, '241.35', 900, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 6000, NULL, 0, 34, '241.35', 900, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 12000, NULL, 0, 41, '241.35', 1800, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 12000, NULL, 0, 42, '241.35', 1800, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 240, NULL, 1, 1, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 600, NULL, 3, 1, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 240, NULL, 1, 2, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 600, NULL, 3, 2, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 240, NULL, 1, 3, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 600, NULL, 3, 3, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 240, NULL, 1, 4, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 240, NULL, 1, 5, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 600, NULL, 3, 5, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 1500, NULL, 0, 6, '241.35', 225, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 240, NULL, 1, 7, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 600, NULL, 3, 7, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 240, NULL, 1, 12, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 600, NULL, 3, 12, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 240, NULL, 1, 13, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 600, NULL, 3, 13, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 240, NULL, 1, 14, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 600, NULL, 3, 14, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 1500, NULL, 0, 21, '241.35', 225, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 1500, NULL, 0, 22, '241.35', 225, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 1500, NULL, 0, 23, '241.35', 225, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 1500, NULL, 0, 24, '241.35', 225, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 1500, NULL, 0, 25, '241.35', 225, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 1500, NULL, 0, 26, '241.35', 225, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 1500, NULL, 0, 27, '241.35', 225, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 1500, NULL, 0, 31, '241.35', 225, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 1500, NULL, 0, 32, '241.35', 225, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 1500, NULL, 0, 33, '241.35', 225, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 1500, NULL, 0, 34, '241.35', 225, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 3000, NULL, 0, 41, '241.35', 450, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 3000, NULL, 0, 42, '241.35', 450, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 120, NULL, 1, 1, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 120, NULL, 1, 2, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 360, NULL, 3, 2, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 120, NULL, 1, 3, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 360, NULL, 3, 3, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 120, NULL, 1, 4, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 360, NULL, 3, 4, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 120, NULL, 1, 5, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 360, NULL, 3, 5, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 1200, NULL, 0, 6, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 120, NULL, 1, 7, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 360, NULL, 3, 7, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 120, NULL, 1, 12, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 120, NULL, 1, 13, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 360, NULL, 3, 13, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 120, NULL, 1, 14, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 360, NULL, 3, 14, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 1200, NULL, 0, 21, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 1200, NULL, 0, 22, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 1200, NULL, 0, 23, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 1200, NULL, 0, 24, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 1200, NULL, 0, 25, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 1200, NULL, 0, 26, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 1200, NULL, 0, 27, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 1200, NULL, 0, 31, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 1200, NULL, 0, 32, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 1200, NULL, 0, 33, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 1200, NULL, 0, 34, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 1200, NULL, 0, 41, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 1200, NULL, 0, 42, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
14, '461', 500, NULL, 1, 0, '0', 0, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
18, '0', 0, NULL, 0, 0, '0', 0, 'Max 30 Day'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
15, '466', 0, NULL, 0, 0, '0', 0, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
14, '461', 1500, NULL, 3, 0, '0', 0, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
13, '259.20', 0, NULL, 0, 0, '241.35', 0, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
17, '0', 240, NULL, 0, 0, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
16, '921', 100, NULL, 0, 0, '0', 0, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
18, '0', 0, NULL, 0, 0, '0', 0, 'After 30 Day'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
10, '208.20', 40, NULL, 0, 0, '0', 0, 'D-11'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
21, '259.20', 0, NULL, 0, 0, '0', 0, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
10, '208.20', 61, NULL, 0, 0, '0', 0, 'D-12'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
10, '208.20', 136, NULL, 0, 0, '0', 0, 'D-14'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
10, '208.20', 81, NULL, 0, 0, '0', 0, 'D-25'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
11, '108.20', 925, NULL, 0, 0, '241.35', 0, 'J-01'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
11, '108.20', 15528, NULL, 0, 0, '241.35', 0, 'J-02'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
11, '108.20', 12700, NULL, 0, 0, '241.35', 0, 'J-03'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
11, '108.20', 20050, NULL, 0, 0, '241.35', 0, 'J-04'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
11, '108.20', 1251, NULL, 0, 0, '241.35', 0, 'J-39'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
11, '108.20', 10912, NULL, 0, 0, '241.35', 0, 'J-16'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
12, '108.20', 4892, NULL, 0, 0, '0', 0, 'J-05'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
12, '108.20', 8975, NULL, 0, 0, '0', 0, 'J-06'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
12, '108.20', 3989, NULL, 0, 0, '0', 0, 'J-17'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
13, '259.20', 650, NULL, 1, 4, '241.35', 98, 'UP'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
13, '259.20', 1600, NULL, 3, 4, '241.35', 240, 'UP'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
13, '259.20', 450, NULL, 1, 4, '241.35', 68, 'DOWN'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
13, '259.20', 1100, NULL, 3, 4, '241.35', 165, 'DOWN'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 960, NULL, 3, 3, '241.35', 144, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 960, NULL, 3, 14, '241.35', 144, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 480, NULL, 3, 7, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 360, NULL, 3, 3, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 360, NULL, 3, 14, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 840, NULL, 3, 7, '241.35', 126, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
8, '461', 600, NULL, 3, 4, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 360, NULL, 3, 1, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
9, '466', 360, NULL, 3, 12, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 120, NULL, 1, 1, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 360, NULL, 3, 1, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 120, NULL, 1, 3, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 120, NULL, 1, 2, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 360, NULL, 3, 2, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 360, NULL, 3, 3, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 120, NULL, 1, 4, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 360, NULL, 3, 4, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 120, NULL, 1, 5, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 360, NULL, 3, 5, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 120, NULL, 1, 7, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 360, NULL, 3, 7, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 120, NULL, 1, 12, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 360, NULL, 3, 12, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 120, NULL, 1, 13, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 360, NULL, 3, 13, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 120, NULL, 1, 14, '241.35', 18, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 360, NULL, 3, 14, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 1200, NULL, 0, 6, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 1200, NULL, 0, 21, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 1200, NULL, 0, 22, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 1200, NULL, 0, 23, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 1200, NULL, 0, 24, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 1200, NULL, 0, 25, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 1200, NULL, 0, 26, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 1200, NULL, 0, 27, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 1200, NULL, 0, 31, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 1200, NULL, 0, 32, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 1200, NULL, 0, 33, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 1200, NULL, 0, 34, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 2400, NULL, 0, 41, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
1, '466', 2400, NULL, 0, 42, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 300, NULL, 1, 1, '241.35', 45, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 600, NULL, 3, 1, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 300, NULL, 1, 2, '241.35', 45, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 600, NULL, 3, 2, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 300, NULL, 1, 3, '241.35', 45, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 600, NULL, 3, 3, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 300, NULL, 1, 4, '241.35', 45, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 600, NULL, 3, 4, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 300, NULL, 1, 5, '241.35', 45, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 600, NULL, 3, 5, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 300, NULL, 1, 12, '241.35', 45, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 600, NULL, 3, 12, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 300, NULL, 1, 7, '241.35', 45, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 600, NULL, 3, 7, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 300, NULL, 1, 13, '241.35', 45, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 600, NULL, 3, 13, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 600, NULL, 3, 14, '241.35', 90, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 300, NULL, 1, 14, '241.35', 45, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 1200, NULL, 0, 6, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 1200, NULL, 0, 21, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 1200, NULL, 0, 22, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 1200, NULL, 0, 23, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 1200, NULL, 0, 24, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 1200, NULL, 0, 25, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 1200, NULL, 0, 26, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
2, '466', 1200, NULL, 0, 27, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 720, NULL, 1, 1, '241.35', 108, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 1920, NULL, 3, 1, '241.35', 288, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 720, NULL, 1, 2, '241.35', 108, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 1920, NULL, 3, 2, '241.35', 288, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 720, NULL, 1, 4, '241.35', 108, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 1920, NULL, 3, 4, '241.35', 288, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 720, NULL, 1, 3, '241.35', 108, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 1920, NULL, 3, 3, '241.35', 288, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 720, NULL, 1, 5, '241.35', 108, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 1920, NULL, 3, 5, '241.35', 288, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 720, NULL, 1, 7, '241.35', 108, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 1920, NULL, 3, 7, '241.35', 288, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 720, NULL, 1, 12, '241.35', 108, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 1920, NULL, 3, 12, '241.35', 288, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 720, NULL, 1, 13, '241.35', 108, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 1920, NULL, 3, 13, '241.35', 288, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 720, NULL, 1, 14, '241.35', 108, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 1920, NULL, 3, 14, '241.35', 288, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 12000, NULL, 0, 22, '241.35', 1800, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 12000, NULL, 0, 23, '241.35', 1800, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 12000, NULL, 0, 6, '241.35', 1800, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 12000, NULL, 0, 21, '241.35', 1800, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 12000, NULL, 0, 24, '241.35', 1800, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 12000, NULL, 0, 25, '241.35', 1800, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 12000, NULL, 0, 26, '241.35', 1800, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 12000, NULL, 0, 27, '241.35', 1800, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 12000, NULL, 0, 31, '241.35', 1800, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 12000, NULL, 0, 32, '241.35', 1800, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 12000, NULL, 0, 33, '241.35', 1800, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 12000, NULL, 0, 34, '241.35', 1800, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 24000, NULL, 0, 41, '241.35', 3600, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
3, '461', 24000, NULL, 0, 42, '241.35', 3600, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 480, NULL, 1, 1, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 960, NULL, 3, 1, '241.35', 144, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 480, NULL, 1, 2, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 960, NULL, 3, 2, '241.35', 144, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 480, NULL, 1, 3, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 480, NULL, 1, 4, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 960, NULL, 3, 4, '241.35', 144, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 960, NULL, 3, 5, '241.35', 144, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 480, NULL, 1, 5, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 480, NULL, 1, 7, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 960, NULL, 3, 7, '241.35', 144, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 480, NULL, 1, 12, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 960, NULL, 3, 12, '241.35', 144, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 480, NULL, 1, 13, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 960, NULL, 3, 13, '241.35', 144, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 480, NULL, 1, 14, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 2400, NULL, 0, 6, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 2400, NULL, 0, 21, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 2400, NULL, 0, 22, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 2400, NULL, 0, 23, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 2400, NULL, 0, 24, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 2400, NULL, 0, 25, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 2400, NULL, 0, 26, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 2400, NULL, 0, 27, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 2400, NULL, 0, 31, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 2400, NULL, 0, 32, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 2400, NULL, 0, 33, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 2400, NULL, 0, 34, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 4800, NULL, 0, 41, '241.35', 720, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
4, '461', 4800, NULL, 0, 42, '241.35', 720, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 240, NULL, 1, 1, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 480, NULL, 3, 1, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 240, NULL, 1, 2, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 480, NULL, 3, 2, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 240, NULL, 1, 3, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 480, NULL, 3, 3, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 240, NULL, 1, 4, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 480, NULL, 3, 4, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 240, NULL, 1, 5, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 480, NULL, 3, 5, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 1200, NULL, 0, 6, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 240, NULL, 1, 7, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 240, NULL, 1, 12, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 480, NULL, 3, 12, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 240, NULL, 1, 13, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 480, NULL, 3, 13, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 240, NULL, 1, 14, '241.35', 36, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 480, NULL, 3, 14, '241.35', 72, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 1200, NULL, 0, 21, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 1200, NULL, 0, 22, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 1200, NULL, 0, 23, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 1200, NULL, 0, 24, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 1200, NULL, 0, 25, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 1200, NULL, 0, 26, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 1200, NULL, 0, 27, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 1200, NULL, 0, 31, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 1200, NULL, 0, 32, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 1200, NULL, 0, 33, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 1200, NULL, 0, 34, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 2400, NULL, 0, 41, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
5, '461', 2400, NULL, 0, 42, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 180, NULL, 1, 1, '241.35', 27, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 360, NULL, 3, 1, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 180, NULL, 1, 2, '241.35', 27, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 360, NULL, 3, 2, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 180, NULL, 1, 3, '241.35', 27, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 180, NULL, 1, 4, '241.35', 27, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 360, NULL, 3, 4, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 180, NULL, 1, 5, '241.35', 27, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 360, NULL, 3, 5, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 1200, NULL, 0, 6, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 180, NULL, 1, 7, '241.35', 27, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 360, NULL, 3, 7, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 180, NULL, 1, 12, '241.35', 27, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 360, NULL, 3, 12, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 180, NULL, 1, 13, '241.35', 27, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 360, NULL, 3, 13, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 180, NULL, 1, 14, '241.35', 27, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 1200, NULL, 0, 21, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 1200, NULL, 0, 22, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 1200, NULL, 0, 23, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 1200, NULL, 0, 24, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 1200, NULL, 0, 25, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 1200, NULL, 0, 26, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 1200, NULL, 0, 27, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 1200, NULL, 0, 31, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 1200, NULL, 0, 32, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 1200, NULL, 0, 33, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 1200, NULL, 0, 34, '241.35', 180, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 2400, NULL, 0, 41, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
6, '466', 2400, NULL, 0, 42, '241.35', 360, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 360, NULL, 1, 1, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 840, NULL, 3, 1, '241.35', 126, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 360, NULL, 1, 2, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 840, NULL, 3, 2, '241.35', 126, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 360, NULL, 1, 3, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 840, NULL, 3, 3, '241.35', 126, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 360, NULL, 1, 4, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 840, NULL, 3, 4, '241.35', 126, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 360, NULL, 1, 5, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 840, NULL, 3, 5, '241.35', 126, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 6000, NULL, 0, 6, '241.35', 900, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 360, NULL, 1, 7, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 360, NULL, 1, 12, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 840, NULL, 3, 12, '241.35', 126, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 360, NULL, 1, 13, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 840, NULL, 3, 13, '241.35', 126, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 360, NULL, 1, 14, '241.35', 54, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 840, NULL, 3, 14, '241.35', 126, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 6000, NULL, 0, 21, '241.35', 900, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 6000, NULL, 0, 22, '241.35', 900, '--'); 
INSERT INTO TBL_ONEPOINT_CMP_CHARGES ( CMP_ID, CHARGE_ACC, CHARGE, ACC_CODE, PHASE, TARIFF_GRP_CODE,
ACC_HEAD, VAT, O_TYPE ) VALUES ( 
7, '466', 6000, NULL, 0, 23, '241.35', 900, '--'); 


COMMIT;

