UPDATE TBL_JMENUS SET MENU_OPTION='20799' WHERE MENU_ID=20;
UPDATE TBL_JMENUS SET MENU_OPTION='1' WHERE MENU_ID=40;
UPDATE TBL_JMENUS SET MENU_OPTION='0' WHERE MENU_ID=123;
UPDATE TBL_JMENUS SET MENU_OPTION='CMP8421002' WHERE MENU_ID=209;

COMMIT;